import { AsyncStateCard } from "../../shared/ui/AsyncStateCard";
import { Plus } from "lucide-react";
import { InlineAlert } from "../../shared/ui/error-ui/components";
import { TableLoadingIndicator } from "../../shared/ui/TableLoadingIndicator";
import { RouteDetailDialog } from "./components/RouteDetailDialog";
import { RouteFilters } from "./components/RouteFilters";
import { RouteTable } from "./components/RouteTable";
import { RouteDraftDialog } from "./components/RouteDraftDialog";
import { RouteOrderEditor } from "./components/RouteOrderEditor";
import { RouteProposalDialog } from "./components/RouteProposalDialog";
import { ModalHeader } from "../../shared/ui/ModalHeader";
import { ModalSurface } from "../../shared/ui/ModalSurface";
import { FormAlert } from "../../shared/ui/FormAlert";
import { OperationDialog } from "../../shared/ui/OperationDialog";
import { getSessionIdentity } from "../auth/auth";
import { useRouteDetail } from "./hooks/useRouteDetail";
import { useRouteDraft } from "./hooks/useRouteDraft";
import { useRoutes } from "./hooks/useRoutes";
import { useRoutePublish } from "./hooks/useRoutePublish";
import { RoutePublishDialog } from "./components/RoutePublishDialog";
import "./styles/company-routes.css";

export function CompanyRoutesPage() {
  const routes = useRoutes(); const detail = useRouteDetail(); const draft = useRouteDraft(routes.retry, routes.sellers); const items = routes.result?.items ?? []; const hasFilters = Boolean(routes.date || routes.sellerId || routes.status); const roles = getSessionIdentity()?.roles ?? []; const canCreate = roles.includes("COMPANY_ADMIN") || roles.includes("SUPERVISOR"); const publish = useRoutePublish(routes.sessionKey, (route) => { detail.replace(route); routes.retry(); }, () => { detail.retry(); routes.retry(); });
  const selectedRoute = detail.route ?? detail.target;
  const selectedSeller = selectedRoute ? routes.sellers.find((seller) => seller.id === selectedRoute.sellerId) : undefined;
  return <section className="route-list" aria-labelledby="route-list-title"><header className="route-list__heading"><div><h1 id="route-list-title">Rutas</h1><p>Consulta las rutas asignadas a los vendedores de la empresa.</p></div>{canCreate && <button className="route-list__primary" type="button" onClick={draft.openForm}><Plus aria-hidden="true" />Crear borrador</button>}</header><section className="route-list__card" aria-label="Listado de rutas"><RouteFilters date={routes.date} sellerId={routes.sellerId} status={routes.status} sellers={routes.sellers} onDateChange={routes.changeDate} onSellerChange={routes.changeSeller} onStatusChange={routes.changeStatus} />
    {routes.error && <InlineAlert variant="error" title={routes.error.status === 403 ? "No tienes permisos" : "Ocurrió un problema temporal"} message={routes.error.status === 403 ? "No tienes permiso para consultar rutas." : "No pudimos actualizar las rutas. Los datos mostrados pueden no estar vigentes."} action={{ label: "Reintentar", onClick: routes.retry }} {...(routes.error.correlationId ? { correlationId: routes.error.correlationId } : {})} />}
    {routes.forbidden ? <AsyncStateCard tone="error" title="No tienes permisos" description="No tienes permiso para consultar rutas." actionLabel="Reintentar" onAction={routes.retry} /> : routes.loading && items.length === 0 ? <TableLoadingIndicator label="Cargando rutas" /> : !routes.error && items.length === 0 ? <AsyncStateCard title={hasFilters ? "No encontramos rutas" : "Aún no hay rutas"} description={hasFilters ? "Prueba con otros filtros." : "Cuando existan rutas aparecerán en este listado."} {...(hasFilters ? { actionLabel: "Limpiar filtros", onAction: routes.clearFilters } : {})} /> : items.length > 0 && <><RouteTable routes={items} sellers={routes.sellers} page={routes.page} pageSize={routes.pageSize} totalPages={routes.result?.page.totalPages ?? 0} totalElements={routes.result?.page.totalElements ?? items.length} lastUpdated={routes.lastUpdated} onDetail={detail.open} onPageChange={routes.goToPage} onPageSizeChange={routes.changePageSize} />{routes.loading && <div className="route-list__stale"><TableLoadingIndicator label="Actualizando rutas; los datos mostrados pueden no estar vigentes" compact /></div>}</>}</section>
    {detail.target && selectedRoute && !publish.route && <RouteDetailDialog target={detail.target} route={detail.route} sellerLabel={selectedSeller?.label ?? "Vendedor no disponible"} sellerAvailable={selectedSeller?.status === "ACTIVE"} loading={detail.loading} error={detail.error} canGenerateProposal={canCreate} canPublish={canCreate} onGenerateProposal={draft.openProposal} onPublish={publish.open} onRetry={detail.retry} onClose={detail.close} />}
    {publish.route && <RoutePublishDialog route={publish.route} sellerLabel={routes.sellers.find((seller) => seller.id === publish.route?.sellerId)?.label ?? "Vendedor no disponible"} sellerAvailable={routes.sellers.some((seller) => seller.id === publish.route?.sellerId && seller.status === "ACTIVE")} notifySeller={publish.notifySeller} busy={publish.busy} error={publish.error} onNotifySeller={publish.setNotifySeller} onClose={publish.close} onConfirm={publish.submit} onReload={() => { publish.close(); detail.retry(); routes.retry(); }} />}
    {publish.published && <OperationDialog titleId="route-publish-success-title" tone="success" title="Ruta publicada" message={`La ruta ${publish.published.name ?? publish.published.date} quedó publicada. ${publish.published.version > 0 ? `Versión ${publish.published.version}.` : ""}`} onClose={publish.closePublished} />}
    {draft.created && <OperationDialog titleId="route-draft-success-title" tone="success" title="Borrador guardado" message={`La ruta ${draft.created.name ?? draft.created.date} se guardó correctamente. Ábrela desde el listado para revisarla y publicarla.`} onClose={draft.closeCreated} />}
    {draft.formOpen && <RouteDraftDialog sellers={routes.sellers} date={draft.date} sellerId={draft.sellerId} customers={draft.customers} selected={draft.selected} serviceDurations={draft.serviceDurations} hasInvalidDurations={draft.hasInvalidDurations} loadingCustomers={draft.loadingCustomers} moreCustomers={draft.moreCustomers} suggestionError={draft.suggestionError} saving={draft.saving} error={draft.error} onDate={draft.setDate} onSeller={draft.setSellerId} onSelected={draft.setSelected} onServiceDuration={draft.setServiceDuration} onSubmit={draft.submit} onLoadMore={draft.loadMore} onRetrySuggestions={draft.retrySuggestions} onRetryCustomers={draft.retryCustomers} onClose={draft.close} />}
    {draft.proposalOpen && draft.draft && <RouteProposalDialog route={draft.draft} availabilityStart={draft.availabilityStart} availabilityEnd={draft.availabilityEnd} visits={draft.proposalVisits} proposal={draft.proposal} validation={draft.proposalValidation} saving={draft.saving} error={draft.error} conflict={draft.conflict} onAvailabilityStart={draft.setAvailabilityStart} onAvailabilityEnd={draft.setAvailabilityEnd} onVisit={draft.updateProposalVisit} onOptimize={draft.optimize} onClose={draft.closeProposal} />}
    {draft.orderOpen && draft.draft && <ModalSurface titleId="route-order-title" onDismiss={draft.closeOrder} className="route-detail route-detail--order"><ModalHeader module="Rutas" title="Ordenar borrador" titleId="route-order-title" onClose={draft.closeOrder} closeDisabled={draft.saving} /><p className="sr-only" role="status" aria-live="polite">{draft.announcement}</p><p className="route-detail__hint" id="route-order-help">Arrastra una visita para cambiar la secuencia. También puedes usar las flechas.</p>{draft.conflict && <FormAlert><strong>No pudimos guardar sobre la versión actual</strong><p>Conservamos el orden que preparaste y actualizamos el borrador. Genera una propuesta nueva antes de persistirla.</p></FormAlert>}{draft.error && <FormAlert><strong>No pudimos guardar el orden</strong><p>Inténtalo nuevamente.</p></FormAlert>}<RouteOrderEditor route={draft.draft} saving={draft.saving} onMove={draft.move} onMoveTo={draft.moveTo} /><footer><button className="route-list__secondary" type="button" onClick={draft.closeOrder} disabled={draft.saving}>Cerrar</button><button className="route-list__secondary" type="button" onClick={draft.openProposalFromOrder} disabled={draft.saving}>Generar propuesta</button><button className="route-list__primary" type="button" onClick={draft.saveOrder} disabled={draft.saving}>{draft.saving ? "Guardando…" : "Guardar orden"}</button></footer></ModalSurface>}
  </section>;
}
