package com.nahui.followupbussiness.identityaccess.persistence;

import com.nahui.followupbussiness.audit.adapter.out.persistence.JdbcAuthenticationAuditAdapter;
import com.nahui.followupbussiness.audit.application.port.in.RecordAuthenticationAuditUseCase;
import com.nahui.followupbussiness.identityaccess.adapter.out.persistence.JdbcLoginAccountQuery;
import com.nahui.followupbussiness.identityaccess.adapter.out.persistence.JdbcRefreshSessionAdapter;
import com.nahui.followupbussiness.identityaccess.application.RefreshService;
import com.nahui.followupbussiness.identityaccess.application.LogoutSessionService;
import com.nahui.followupbussiness.identityaccess.application.port.in.LogoutSessionUseCase;
import com.nahui.followupbussiness.identityaccess.config.AuthenticationProperties;
import com.nahui.followupbussiness.identityaccess.config.LoginConfiguration;
import com.nahui.followupbussiness.identityaccess.domain.model.AuthenticatedActor;
import com.nahui.followupbussiness.identityaccess.domain.model.BaseRole;
import com.nahui.followupbussiness.notifications.adapter.out.persistence.JdbcInstallationRevocationAdapter;
import com.nahui.followupbussiness.identityaccess.application.port.out.RefreshRateLimitPort;
import com.nahui.followupbussiness.identityaccess.adapter.out.security.Rs256AccessTokenAdapter;
import java.nio.charset.StandardCharsets;
import java.security.KeyPairGenerator;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.*;
import java.util.concurrent.*;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.transaction.support.TransactionTemplate;
import org.testcontainers.postgresql.PostgreSQLContainer;
import org.testcontainers.utility.DockerImageName;
import static org.assertj.core.api.Assertions.*;

class RefreshSessionTransactionIntegrationTest {
 private static final DockerImageName IMAGE=DockerImageName.parse("postgis/postgis:17-3.5").asCompatibleSubstituteFor("postgres");
 private static PostgreSQLContainer postgres; private JdbcTemplate jdbc; private TransactionTemplate tx; private UUID account,company,family,client; private final Instant now=Instant.parse("2026-08-04T12:00:00Z"); private final String refresh="A".repeat(43); private static final byte[] KEY="01234567890123456789012345678901".getBytes(StandardCharsets.UTF_8);
 @BeforeAll static void start(){postgres=new PostgreSQLContainer(IMAGE).withDatabaseName("be004_refresh").withUsername("be004").withPassword("be004");postgres.start();}
 @AfterAll static void stop(){if(postgres!=null)postgres.stop();}
 @BeforeEach void clean(){var ds=new DriverManagerDataSource(postgres.getJdbcUrl(),postgres.getUsername(),postgres.getPassword());Flyway.configure().dataSource(ds).locations("classpath:db/migration").cleanDisabled(false).load().clean();Flyway.configure().dataSource(ds).locations("classpath:db/migration").load().migrate();jdbc=new JdbcTemplate(ds);tx=new TransactionTemplate(new DataSourceTransactionManager(ds));account=UUID.randomUUID();company=UUID.randomUUID();family=UUID.randomUUID();client=UUID.randomUUID();jdbc.update("INSERT INTO tenancy_company(id,status,created_at,updated_at) VALUES (?,'ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",company);jdbc.update("INSERT INTO identity_access_account(id,login_identifier,password_hash,role_code,company_id,status,display_name,email,created_at,updated_at) VALUES (?,?,?,'SELLER',?,'ACTIVE','User','u@example.test',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",account,"u@example.test","$2a$12$7EqJtq98hPqEX7fNZaFWoO9fkg8rDs3umP5e0yZG5qR1zwVmzEoOe",company);jdbc.update("INSERT INTO identity_access_session_family(id,account_id,company_id,channel,client_instance_digest,refresh_token_digest,expires_at,created_at) VALUES (?,?,?,'MOBILE',?,?,?,?)",family,account,company,hmac(client.toString()),hmac(refresh),java.sql.Timestamp.from(now.plusSeconds(2592000)),java.sql.Timestamp.from(now));}
 @Test void concurrentRefreshCreatesOneSuccessorAndOneContractualReplay(){var service=service(new JdbcAuthenticationAuditAdapter(jdbc));var gate=new CountDownLatch(1);UUID correlation=UUID.randomUUID();try(var pool=Executors.newFixedThreadPool(2)){var first=pool.submit(()->call(service,gate,correlation));var second=pool.submit(()->call(service,gate,correlation));gate.countDown();var outcomes=List.of(first.get(),second.get());assertThat(outcomes.stream().filter(x->x.equals("OK")).count()).isEqualTo(1);assertThat(outcomes.stream().filter(x->x.equals("ALREADY_ROTATED")).count()).isEqualTo(1);}catch(Exception e){throw new AssertionError(e);}assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM identity_access_consumed_refresh_token WHERE family_id=?",Integer.class,family)).isEqualTo(1);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM audit_entry WHERE resource_id=?",Integer.class,family)).isEqualTo(2);var replay=jdbc.queryForMap("SELECT correlation_id,after_state::text FROM audit_entry WHERE resource_id=? AND after_state->>'result'='ALREADY_ROTATED'",family);assertThat(replay.get("correlation_id")).isEqualTo(correlation);assertThat(replay.get("after_state").toString()).contains("REPLAY").doesNotContain(refresh);}
 @Test void webRefreshRotatesCsrfAndRejectsThePreviousValue(){jdbc.update("UPDATE identity_access_session_family SET channel='WEB',csrf_token_digest=? WHERE id=?",hmac("C0"),family);var service=service(new JdbcAuthenticationAuditAdapter(jdbc));var first=tx.execute(s->service.refresh(command(refresh,"C0",UUID.randomUUID())));var second=tx.execute(s->service.refresh(command(first.refreshToken(),first.csrfToken(),UUID.randomUUID())));assertThat(first.csrfToken()).isNotEqualTo("C0");assertThat(second.csrfToken()).isNotEqualTo(first.csrfToken());assertThatThrownBy(()->tx.execute(s->service.refresh(command(second.refreshToken(),"C0",UUID.randomUUID())))).isInstanceOf(RefreshService.Rejected.class);}
 @Test void auditFailureRollsBackConsumedDigestAndSuccessor(){var service=service(c->{throw new IllegalStateException("audit failure");});assertThatThrownBy(()->tx.execute(s->service.refresh(command()))).isInstanceOf(IllegalStateException.class);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM identity_access_consumed_refresh_token WHERE family_id=?",Integer.class,family)).isZero();assertThat(jdbc.queryForObject("SELECT refresh_token_digest FROM identity_access_session_family WHERE id=?",byte[].class,family)).isEqualTo(hmac(refresh));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM audit_entry WHERE resource_id=?",Integer.class,family)).isZero();}
 @Test void platformSessionWithoutTenantRefreshesAndLogsOutWithTenantlessAuthenticationAudit(){jdbc.update("UPDATE identity_access_account SET role_code='PLATFORM_SUPERADMIN',company_id=NULL WHERE id=?",account);jdbc.update("UPDATE identity_access_session_family SET company_id=NULL WHERE id=?",family);var refreshed=tx.execute(s->service(new JdbcAuthenticationAuditAdapter(jdbc)).refresh(command()));assertThat(refreshed.account().companyId()).isNull();var logout=new LogoutSessionService(new JdbcRefreshSessionAdapter(jdbc),new JdbcAuthenticationAuditAdapter(jdbc),Clock.fixed(now,ZoneOffset.UTC),KEY);tx.executeWithoutResult(s->logout.logout(new LogoutSessionUseCase.Command(new AuthenticatedActor(account,null,BaseRole.PLATFORM_SUPERADMIN,family),false,null,null,null,UUID.randomUUID())));assertThat(jdbc.queryForObject("SELECT revoked_at IS NOT NULL FROM identity_access_session_family WHERE id=?",Boolean.class,family)).isTrue();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM audit_entry WHERE tenant_id IS NULL AND scope='ANONYMOUS_AUTH' AND resource_id=?",Integer.class,family)).isEqualTo(2);}
 @Test void platformLogoutCommitsRevocationWhenFinalAuditFails(){jdbc.update("UPDATE identity_access_account SET role_code='PLATFORM_SUPERADMIN',company_id=NULL WHERE id=?",account);jdbc.update("UPDATE identity_access_session_family SET company_id=NULL,expires_at=CURRENT_TIMESTAMP + INTERVAL '1 day' WHERE id=?",family);var logout=configuredLogout(c->{throw new IllegalStateException("audit failure");});assertThatThrownBy(()->logout.logout(new LogoutSessionUseCase.Command(new AuthenticatedActor(account,null,BaseRole.PLATFORM_SUPERADMIN,family),false,null,null,null,UUID.randomUUID()))).isInstanceOf(LogoutSessionService.AuditUnavailableAfterRevocation.class);assertThat(jdbc.queryForObject("SELECT revoked_at IS NOT NULL FROM identity_access_session_family WHERE id=?",Boolean.class,family)).isTrue();}
 @Test void logoutRevokesOnlyAuthenticatedTenantFamiliesDurablyAndIdempotently(){UUID other=UUID.randomUUID(),otherTenant=UUID.randomUUID(),otherAccount=UUID.randomUUID(),foreignFamily=UUID.randomUUID();jdbc.update("INSERT INTO identity_access_session_family(id,account_id,company_id,channel,client_instance_digest,refresh_token_digest,expires_at,created_at) VALUES (?,?,?,'MOBILE',?,?,?,?)",other,account,company,hmac("other"),hmac("other-refresh"),java.sql.Timestamp.from(now.plusSeconds(60)),java.sql.Timestamp.from(now));jdbc.update("INSERT INTO tenancy_company(id,status,created_at,updated_at) VALUES (?,'ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",otherTenant);jdbc.update("INSERT INTO identity_access_account(id,login_identifier,password_hash,role_code,company_id,status,display_name,email,created_at,updated_at) VALUES (?,?,?,'SELLER',?,'ACTIVE','Foreign','foreign@example.test',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",otherAccount,"foreign@example.test","$2a$12$7EqJtq98hPqEX7fNZaFWoO9fkg8rDs3umP5e0yZG5qR1zwVmzEoOe",otherTenant);jdbc.update("INSERT INTO identity_access_session_family(id,account_id,company_id,channel,client_instance_digest,refresh_token_digest,expires_at,created_at) VALUES (?,?,?,'MOBILE',?,?,?,?)",foreignFamily,otherAccount,otherTenant,hmac("foreign"),hmac("foreign-refresh"),java.sql.Timestamp.from(now.plusSeconds(60)),java.sql.Timestamp.from(now));var logout=new LogoutSessionService(new JdbcRefreshSessionAdapter(jdbc),new JdbcAuthenticationAuditAdapter(jdbc),Clock.fixed(now,ZoneOffset.UTC),KEY);var actor=new AuthenticatedActor(account,company,BaseRole.SELLER,family);tx.executeWithoutResult(s->logout.logout(new LogoutSessionUseCase.Command(actor,true,null,null,null,UUID.randomUUID())));tx.executeWithoutResult(s->logout.logout(new LogoutSessionUseCase.Command(actor,true,null,null,null,UUID.randomUUID())));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM identity_access_session_family WHERE account_id=? AND company_id=? AND revoked_at IS NOT NULL",Integer.class,account,company)).isEqualTo(2);assertThat(jdbc.queryForObject("SELECT revoked_at IS NULL FROM identity_access_session_family WHERE id=?",Boolean.class,foreignFamily)).isTrue();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM audit_entry WHERE resource_id=?",Integer.class,family)).isEqualTo(2);}
 @Test void expiredMobilePendingTicketDoesNotRevoke(){jdbc.update("UPDATE identity_access_session_family SET revocation_ticket_digest=?,expires_at=? WHERE id=?",hmac("expired-ticket"),java.sql.Timestamp.from(now),family);var logout=new LogoutSessionService(new JdbcRefreshSessionAdapter(jdbc),new JdbcAuthenticationAuditAdapter(jdbc),Clock.fixed(now,ZoneOffset.UTC),KEY);assertThatThrownBy(()->tx.executeWithoutResult(s->logout.logout(new LogoutSessionUseCase.Command(null,false,null,"expired-ticket",null,UUID.randomUUID())))).isInstanceOf(LogoutSessionService.Rejected.class);assertThat(jdbc.queryForObject("SELECT revoked_at IS NULL FROM identity_access_session_family WHERE id=?",Boolean.class,family)).isTrue();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM audit_entry WHERE resource_id=?",Integer.class,family)).isZero();}
 @Test void mobilePendingTicketIsConsumedAndReplayIsRejectedWithoutAnotherAudit(){jdbc.update("UPDATE identity_access_session_family SET revocation_ticket_digest=? WHERE id=?",hmac("ticket"),family);var logout=new LogoutSessionService(new JdbcRefreshSessionAdapter(jdbc),new JdbcAuthenticationAuditAdapter(jdbc),Clock.fixed(now,ZoneOffset.UTC),KEY);tx.executeWithoutResult(s->logout.logout(new LogoutSessionUseCase.Command(null,false,null,"ticket",null,UUID.randomUUID())));assertThatThrownBy(()->tx.executeWithoutResult(s->logout.logout(new LogoutSessionUseCase.Command(null,false,null,"ticket",null,UUID.randomUUID())))).isInstanceOf(LogoutSessionService.Rejected.class);assertThat(jdbc.queryForObject("SELECT revoked_at IS NOT NULL FROM identity_access_session_family WHERE id=?",Boolean.class,family)).isTrue();assertThat(jdbc.queryForObject("SELECT revocation_ticket_digest IS NULL FROM identity_access_session_family WHERE id=?",Boolean.class,family)).isTrue();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM audit_entry WHERE resource_id=?",Integer.class,family)).isEqualTo(1);}
 @Test void webBoundRevocationTicketIsRejectedWithoutMutatingItsFamily(){jdbc.update("UPDATE identity_access_session_family SET channel='WEB',revocation_ticket_digest=? WHERE id=?",hmac("web-ticket"),family);var logout=new LogoutSessionService(new JdbcRefreshSessionAdapter(jdbc),new JdbcAuthenticationAuditAdapter(jdbc),Clock.fixed(now,ZoneOffset.UTC),KEY);assertThatThrownBy(()->tx.executeWithoutResult(s->logout.logout(new LogoutSessionUseCase.Command(null,false,null,"web-ticket",null,UUID.randomUUID())))).isInstanceOf(LogoutSessionService.Rejected.class);assertThat(jdbc.queryForObject("SELECT revoked_at IS NULL FROM identity_access_session_family WHERE id=?",Boolean.class,family)).isTrue();assertThat(jdbc.queryForObject("SELECT revocation_ticket_digest FROM identity_access_session_family WHERE id=?",byte[].class,family)).isEqualTo(hmac("web-ticket"));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM audit_entry WHERE resource_id=?",Integer.class,family)).isZero();}
 @Test void mobilePendingRollbackRestoresDigestWhenInstallationOrAuditFails(){jdbc.update("UPDATE identity_access_session_family SET revocation_ticket_digest=? WHERE id=?",hmac("installation-failure"),family);var installationFailure=new LogoutSessionService(new JdbcRefreshSessionAdapter(jdbc),new JdbcAuthenticationAuditAdapter(jdbc),(accountId,tenantId)->new com.nahui.followupbussiness.identityaccess.application.port.out.LogoutAbuseMonitor.Decision(false,0),(familyId,tenantId)->{throw new IllegalStateException("installation failure");},Clock.fixed(now,ZoneOffset.UTC),KEY);assertThatThrownBy(()->tx.executeWithoutResult(s->installationFailure.logout(new LogoutSessionUseCase.Command(null,false,null,"installation-failure",null,UUID.randomUUID())))).isInstanceOf(IllegalStateException.class);assertPendingTicketUnchanged("installation-failure");jdbc.update("UPDATE identity_access_session_family SET revocation_ticket_digest=? WHERE id=?",hmac("audit-failure"),family);var auditFailure=new LogoutSessionService(new JdbcRefreshSessionAdapter(jdbc),command->{throw new IllegalStateException("audit failure");},Clock.fixed(now,ZoneOffset.UTC),KEY);assertThatThrownBy(()->tx.executeWithoutResult(s->auditFailure.logout(new LogoutSessionUseCase.Command(null,false,null,"audit-failure",null,UUID.randomUUID())))).isInstanceOf(IllegalStateException.class);assertPendingTicketUnchanged("audit-failure");}
 @Test void concurrentMobileTicketConsumptionHasOneWinnerAndLeavesOtherTenantUntouched(){UUID foreignTenant=UUID.randomUUID(),foreignAccount=UUID.randomUUID(),foreignFamily=UUID.randomUUID();jdbc.update("INSERT INTO tenancy_company(id,status,created_at,updated_at) VALUES (?,'ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",foreignTenant);jdbc.update("INSERT INTO identity_access_account(id,login_identifier,password_hash,role_code,company_id,status,display_name,email,created_at,updated_at) VALUES (?,?,?,'SELLER',?,'ACTIVE','Foreign','foreign@example.test',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",foreignAccount,"foreign@example.test","$2a$12$7EqJtq98hPqEX7fNZaFWoO9fkg8rDs3umP5e0yZG5qR1zwVmzEoOe",foreignTenant);jdbc.update("INSERT INTO identity_access_session_family(id,account_id,company_id,channel,client_instance_digest,refresh_token_digest,revocation_ticket_digest,expires_at,created_at) VALUES (?,?,?,'MOBILE',?,?,?,?,?)",foreignFamily,foreignAccount,foreignTenant,hmac("foreign-client"),hmac("foreign-refresh"),hmac("foreign-ticket"),java.sql.Timestamp.from(now.plusSeconds(60)),java.sql.Timestamp.from(now));jdbc.update("UPDATE identity_access_session_family SET revocation_ticket_digest=? WHERE id=?",hmac("shared-ticket"),family);var installationCalls=new java.util.concurrent.atomic.AtomicInteger();var logout=new LogoutSessionService(new JdbcRefreshSessionAdapter(jdbc),new JdbcAuthenticationAuditAdapter(jdbc),(accountId,tenantId)->new com.nahui.followupbussiness.identityaccess.application.port.out.LogoutAbuseMonitor.Decision(false,0),(familyId,tenantId)->installationCalls.incrementAndGet(),Clock.fixed(now,ZoneOffset.UTC),KEY);var gate=new CountDownLatch(1);try(var pool=Executors.newFixedThreadPool(2)){var first=pool.submit(()->pendingOutcome(logout,gate,"shared-ticket"));var second=pool.submit(()->pendingOutcome(logout,gate,"shared-ticket"));gate.countDown();assertThat(List.of(first.get(),second.get())).containsExactlyInAnyOrder("CONSUMED","REJECTED");}catch(Exception e){throw new AssertionError(e);}assertThat(installationCalls).hasValue(1);assertThat(jdbc.queryForObject("SELECT revoked_at IS NOT NULL FROM identity_access_session_family WHERE id=?",Boolean.class,family)).isTrue();assertThat(jdbc.queryForObject("SELECT revocation_ticket_digest IS NULL FROM identity_access_session_family WHERE id=?",Boolean.class,family)).isTrue();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM audit_entry WHERE resource_id=?",Integer.class,family)).isEqualTo(1);assertThat(jdbc.queryForObject("SELECT revoked_at IS NULL FROM identity_access_session_family WHERE id=?",Boolean.class,foreignFamily)).isTrue();assertThat(jdbc.queryForObject("SELECT revocation_ticket_digest FROM identity_access_session_family WHERE id=?",byte[].class,foreignFamily)).isEqualTo(hmac("foreign-ticket"));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM audit_entry WHERE resource_id=?",Integer.class,foreignFamily)).isZero();}
 @Test void auditFailureRollsBackLogoutRevocation(){var logout=new LogoutSessionService(new JdbcRefreshSessionAdapter(jdbc),c->{throw new IllegalStateException("audit failure");},Clock.fixed(now,ZoneOffset.UTC),KEY);var actor=new AuthenticatedActor(account,company,BaseRole.SELLER,family);assertThatThrownBy(()->tx.executeWithoutResult(s->logout.logout(new LogoutSessionUseCase.Command(actor,false,null,null,null,UUID.randomUUID())))).isInstanceOf(IllegalStateException.class);assertThat(jdbc.queryForObject("SELECT revoked_at IS NULL FROM identity_access_session_family WHERE id=?",Boolean.class,family)).isTrue();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM audit_entry WHERE resource_id=?",Integer.class,family)).isZero();}
 @Test void concurrentRefreshAndLogoutAlwaysEndsRevokedAndRejectsAnyLaterRefresh(){var refreshService=service(new JdbcAuthenticationAuditAdapter(jdbc));var logout=new LogoutSessionService(new JdbcRefreshSessionAdapter(jdbc),new JdbcAuthenticationAuditAdapter(jdbc),Clock.fixed(now,ZoneOffset.UTC),KEY);var gate=new CountDownLatch(1);try(var pool=Executors.newFixedThreadPool(2)){var r=pool.submit(()->{gate.await();try{execute(refreshService,UUID.randomUUID());}catch(RefreshService.Rejected ignored){}return null;});var l=pool.submit(()->{gate.await();tx.executeWithoutResult(s->logout.logout(new LogoutSessionUseCase.Command(new AuthenticatedActor(account,company,BaseRole.SELLER,family),false,null,null,null,UUID.randomUUID())));return null;});gate.countDown();r.get();l.get();}catch(Exception e){throw new AssertionError(e);}assertThat(jdbc.queryForObject("SELECT revoked_at IS NOT NULL FROM identity_access_session_family WHERE id=?",Boolean.class,family)).isTrue();assertThatThrownBy(()->execute(refreshService,UUID.randomUUID())).isInstanceOf(RefreshService.Rejected.class);}
 @Test void mobilePendingAndGlobalRevokeOnlyTechnicalInstallationsInOwnTenant(){UUID other=UUID.randomUUID(),foreign=UUID.randomUUID();jdbc.update("INSERT INTO identity_access_session_family(id,account_id,company_id,channel,client_instance_digest,refresh_token_digest,expires_at,created_at) VALUES (?,?,?,'MOBILE',?,?,?,?)",other,account,company,hmac("other-client"),hmac("other-token"),java.sql.Timestamp.from(now.plusSeconds(60)),java.sql.Timestamp.from(now));jdbc.update("INSERT INTO notification_installation(id,tenant_id,session_family_id) VALUES (?,?,?)",UUID.randomUUID(),company,family);jdbc.update("INSERT INTO notification_installation(id,tenant_id,session_family_id) VALUES (?,?,?)",UUID.randomUUID(),company,other);jdbc.update("INSERT INTO notification_installation(id,tenant_id,session_family_id) VALUES (?,?,?)",UUID.randomUUID(),UUID.randomUUID(),foreign);jdbc.update("UPDATE identity_access_session_family SET revocation_ticket_digest=? WHERE id=?",hmac("ticket"),family);var logout=new LogoutSessionService(new JdbcRefreshSessionAdapter(jdbc),new JdbcAuthenticationAuditAdapter(jdbc),(a,t)->new com.nahui.followupbussiness.identityaccess.application.port.out.LogoutAbuseMonitor.Decision(false,0),new JdbcInstallationRevocationAdapter(jdbc),Clock.fixed(now,ZoneOffset.UTC),KEY);tx.executeWithoutResult(s->logout.logout(new LogoutSessionUseCase.Command(null,false,null,"ticket",null,UUID.randomUUID())));tx.executeWithoutResult(s->logout.logout(new LogoutSessionUseCase.Command(new AuthenticatedActor(account,company,BaseRole.SELLER,family),true,null,null,null,UUID.randomUUID())));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM notification_installation WHERE tenant_id=? AND revoked_at IS NOT NULL",Integer.class,company)).isEqualTo(2);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM notification_installation WHERE session_family_id=? AND revoked_at IS NULL",Integer.class,foreign)).isEqualTo(1);}
 private String call(RefreshService s,CountDownLatch gate,UUID correlation)throws Exception{gate.await();try{execute(s,correlation);return "OK";}catch(RefreshService.Rejected e){return e.code.name();}}
 private RefreshService.Result execute(RefreshService service,UUID correlation){Object outcome=tx.execute(status->{try{return service.refresh(command(refresh,null,correlation));}catch(RefreshService.Rejected rejected){return rejected;}});if(outcome instanceof RefreshService.Rejected rejected)throw rejected;return (RefreshService.Result)outcome;}
 private String pendingOutcome(LogoutSessionService logout,CountDownLatch gate,String ticket)throws Exception{gate.await();try{tx.executeWithoutResult(s->logout.logout(new LogoutSessionUseCase.Command(null,false,null,ticket,null,UUID.randomUUID())));return "CONSUMED";}catch(LogoutSessionService.Rejected rejected){return "REJECTED";}}
 private void assertPendingTicketUnchanged(String ticket){assertThat(jdbc.queryForObject("SELECT revoked_at IS NULL FROM identity_access_session_family WHERE id=?",Boolean.class,family)).isTrue();assertThat(jdbc.queryForObject("SELECT revocation_ticket_digest FROM identity_access_session_family WHERE id=?",byte[].class,family)).isEqualTo(hmac(ticket));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM audit_entry WHERE resource_id=?",Integer.class,family)).isZero();}
 private LogoutSessionUseCase configuredLogout(RecordAuthenticationAuditUseCase audit){try{var properties=new AuthenticationProperties.Values();properties.setHmacSecret(new String(KEY,StandardCharsets.UTF_8));var method=LoginConfiguration.class.getDeclaredMethod("logoutSessionUseCase",JdbcTemplate.class,RecordAuthenticationAuditUseCase.class,StringRedisTemplate.class,com.nahui.followupbussiness.notifications.application.port.in.RevokeInstallationsForSession.class,AuthenticationProperties.Values.class);method.setAccessible(true);com.nahui.followupbussiness.notifications.application.port.in.RevokeInstallationsForSession installations=(familyId,tenantId)->{};return (LogoutSessionUseCase) method.invoke(new LoginConfiguration(),new Object[]{jdbc,audit,org.mockito.Mockito.mock(StringRedisTemplate.class),installations,properties});}catch(ReflectiveOperationException e){throw new AssertionError(e);}}
 private RefreshService service(RecordAuthenticationAuditUseCase audit){try{var keys=KeyPairGenerator.getInstance("RSA");keys.initialize(2048);var port=(RefreshRateLimitPort)(id,ip)->new RefreshRateLimitPort.Decision(true,1);return new RefreshService(new JdbcRefreshSessionAdapter(jdbc),new JdbcLoginAccountQuery(jdbc),id->true,new Rs256AccessTokenAdapter(keys.generateKeyPair().getPrivate(),"kid","issuer","aud",Clock.fixed(now,ZoneOffset.UTC)),audit,port,Clock.fixed(now,ZoneOffset.UTC),KEY);}catch(Exception e){throw new AssertionError(e);}}
 private RefreshService.Command command(){return command(refresh,null,UUID.randomUUID());} private RefreshService.Command command(String token,String csrf,UUID correlation){String channel=csrf==null?"MOBILE":"WEB";return new RefreshService.Command(token,csrf,channel,client,correlation,"127.0.0.1");}
 private static byte[] hmac(String value){try{var m=Mac.getInstance("HmacSHA256");m.init(new SecretKeySpec(KEY,"HmacSHA256"));return m.doFinal(value.getBytes(StandardCharsets.UTF_8));}catch(Exception e){throw new AssertionError(e);}}
}
