import { ArrowLeft, CheckCircle2, CircleAlert, Download, FileWarning, LoaderCircle, RefreshCw } from "lucide-react";
import { InlineAlert } from "../../shared/ui/error-ui/components";
import { Button } from "../../shared/ui/Button";
import { navigate } from "../../app/navigation";
import { useCustomerImportResult } from "./hooks/useCustomerImportResult";
import "./styles/company-client-import-result.css";

const statusCopy = {
  PENDING: ["Importación pendiente", "Recibimos el archivo y estamos preparando su procesamiento.", "Pendiente", "neutral"], PROCESSING: ["Procesando importación", "Estamos validando las filas del archivo.", "Procesando", "info"], COMPLETED: ["Importación completada", "El procesamiento terminó correctamente.", "Completada", "success"], COMPLETED_WITH_ERRORS: ["Importación completada con rechazos", "Puedes revisar las filas rechazadas en el archivo de errores.", "Con rechazos", "warning"], FAILED: ["No pudimos procesar el archivo", "El procesamiento terminó sin completar la importación.", "Fallida", "danger"],
} as const;
function displayDate(value: string | null) { if (value === null || Number.isNaN(Date.parse(value))) return "No disponible"; return new Intl.DateTimeFormat("es-PE", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function errorMessage(status: number) { return status === 400 ? "No pudimos procesar la consulta. Inténtalo nuevamente." : "No pudimos actualizar el resultado. Inténtalo nuevamente."; }
function ValidTime({ value }: { value: string | null }) { return value !== null && !Number.isNaN(Date.parse(value)) ? <time dateTime={value}>{displayDate(value)}</time> : <>No disponible</>; }
function StatePanel({ title, description, loading = false, action }: { title: string; description: string; loading?: boolean; action?: { label: string; onClick: () => void } }) { return <section className="customer-import-result__panel customer-import-result__standalone" aria-busy={loading}><div>{loading ? <LoaderCircle className="customer-import-result__spinner" aria-hidden="true" /> : <CircleAlert aria-hidden="true" />}<h2>{title}</h2><p>{description}</p>{loading ? <span className="sr-only" role="status">Cargando resultado de importación</span> : null}{action ? <Button variant="primary" onClick={action.onClick}>{action.label}</Button> : null}</div></section>; }

export function CompanyClientImportResultPage({ importId }: { importId: string }) {
  const result = useCustomerImportResult(importId);
  const heading = <header className="customer-import-result__heading"><h1 id="customer-import-result-title">Resultado de importación</h1><p>Consulta el avance y el resumen del archivo enviado.</p></header>;
  if (result.forbidden) return <section className="customer-import-result">{heading}<StatePanel title="No tienes permisos" description="El resultado de importación está disponible únicamente para administradores de empresa. No conservamos métricas ni datos previos al cambiar de sesión o perfil." action={{ label: "Volver a clientes", onClick: () => navigate("/company/clients") }} /></section>;
  if (result.job === null && !result.loading && result.error?.status === 404) return <section className="customer-import-result">{heading}<StatePanel title="No encontramos la importación" description="La importación no existe o ya no está disponible." action={{ label: "Volver a la carga", onClick: () => navigate("/company/customer-imports") }} /></section>;
  if (result.loading && result.job === null) return <section className="customer-import-result" aria-labelledby="customer-import-result-title">{heading}<StatePanel loading title="Cargando resultado" description="Estamos consultando el estado de la importación." /></section>;
  if (result.job === null) return <section className="customer-import-result" aria-labelledby="customer-import-result-title">{heading}<StatePanel title="No pudimos consultar el resultado" description={errorMessage(result.error?.status ?? 500)} action={{ label: "Reintentar", onClick: () => void result.refresh() }} /></section>;
  const invalidTemplate = result.job.status === "FAILED" && result.job.failureReason === "INVALID_TEMPLATE";
  const [title, description, badge, tone] = invalidTemplate ? ["La plantilla no tiene el formato esperado", "Descarga una plantilla vigente y copia los datos sin modificar la fila de versión ni las cabeceras.", "Fallida", "danger"] as const : statusCopy[result.job.status];
  const canDownload = result.job.rejectedRows > 0 && !result.polling;
  const unavailableText = result.expired ? "El archivo de errores venció y no puede descargarse." : "El archivo de errores no está disponible.";
  return <section className="customer-import-result" aria-labelledby="customer-import-result-title">
    {heading}<article className="customer-import-result__panel" aria-busy={result.polling}>
      <header className="customer-import-result__status"><span className={`customer-import-result__icon customer-import-result__icon--${tone}`} aria-hidden="true">{tone === "success" ? <CheckCircle2 /> : tone === "warning" || tone === "danger" ? <CircleAlert /> : <FileWarning />}</span><div><div className={`customer-import-result__badge customer-import-result__badge--${tone}`}>{badge}</div><h2>{title}</h2><p>{description}</p></div><div className="customer-import-result__meta">{result.polling ? <span role="status" aria-live="polite"><RefreshCw className="customer-import-result__spinner" aria-hidden="true" />Actualizando estado</span> : null}<p>Última actualización: <ValidTime value={result.lastUpdatedAt} /></p></div></header>
      <div className="customer-import-result__body">
        {result.stale ? <InlineAlert variant="warning" title="Información sin actualizar" message="Mostramos el último resultado disponible. Intenta actualizarlo nuevamente." action={{ label: "Actualizar", onClick: () => void result.refresh() }} {...(result.error?.correlationId ? { correlationId: result.error.correlationId } : {})} /> : null}
        {result.polling ? <p className="customer-import-result__server-note">El proceso continúa en el servidor aunque salgas de esta pantalla.</p> : null}
        {result.job.status === "FAILED" ? <InlineAlert variant="error" title={invalidTemplate ? "Usa una plantilla vigente" : "No se completó la importación"} message={invalidTemplate ? "Vuelve a Carga de clientes, descarga la plantilla actual y crea una importación nueva." : "Vuelve a Carga de clientes para crear una importación nueva. Si el problema continúa, comparte el Correlation ID con soporte."} /> : null}
        <dl className="customer-import-result__metrics"><div><dt>Filas recibidas</dt><dd>{result.job.totalRows ?? "No disponible"}</dd></div><div className="customer-import-result__metric--success"><dt>Aceptadas</dt><dd>{result.job.acceptedRows}</dd></div><div className="customer-import-result__metric--warning"><dt>Rechazadas</dt><dd>{result.job.rejectedRows}</dd></div></dl>
        {canDownload ? <section className="customer-import-result__file" aria-labelledby="errors-file-title"><div><h3 id="errors-file-title">Archivo de filas rechazadas</h3><span className={`customer-import-result__badge customer-import-result__badge--${result.downloading ? "info" : result.fileUnavailable || result.expired ? "neutral" : "success"}`}>{result.downloading ? "Descargando" : result.expired ? "Vencido" : result.fileUnavailable ? "No disponible" : "Disponible"}</span><p>{result.fileUnavailable || result.expired ? unavailableText : result.downloaded ? "Descarga completada. Puedes descargar el archivo nuevamente mientras esté disponible." : result.job.errorFileExpiresAt ? <>Disponible hasta <strong><ValidTime value={result.job.errorFileExpiresAt} /></strong>.</> : "Archivo listo para descargar mientras el servidor lo conserve."}</p></div><Button onClick={() => void result.downloadErrors()} disabled={result.downloading || result.fileUnavailable || result.expired} aria-busy={result.downloading} leadingIcon={<Download aria-hidden="true" />}>{result.downloading ? "Descargando…" : result.downloaded ? "Descargar nuevamente" : "Descargar errores"}</Button></section> : null}
        {result.fileUnavailable || result.expired ? <InlineAlert variant="warning" title={result.expired ? "Archivo vencido" : "Archivo no disponible"} message={unavailableText} /> : null}
        {result.error !== null && !result.stale && result.error.status !== 404 ? <InlineAlert variant="error" title="No pudimos descargar el archivo" message={errorMessage(result.error.status)} action={{ label: "Reintentar", onClick: () => void result.downloadErrors() }} {...(result.error.correlationId ? { correlationId: result.error.correlationId } : {})} /> : null}
      </div><footer className="customer-import-result__actions"><p>{result.polling ? "Puedes actualizar manualmente sin interrumpir el procesamiento." : result.stale ? "Mostramos la última información confirmada." : "El trabajo llegó a un estado terminal. La actualización automática está detenida."}</p><div>{result.polling || result.stale ? <Button variant="primary" onClick={() => void result.refresh()}>Actualizar</Button> : null}<Button variant="primary" onClick={() => navigate("/company/customer-imports")} leadingIcon={<ArrowLeft aria-hidden="true" />}>Volver a cargas</Button></div></footer>
    </article>
  </section>;
}
