import { beforeEach, expect, test, vi } from "vitest";
import { assignBatch, assignOne } from "./api";
const state = vi.hoisted(() => ({ request: vi.fn(), normalize: vi.fn() }));
vi.mock("../../lib/api", () => ({ apiRequest: state.request, normalizeApiError: state.normalize }));
vi.mock("../auth/auth", () => ({ getSessionAuthorization: () => ({ Authorization: "Bearer test" }), getSessionMutationAuthorization: () => ({ Authorization: "Bearer test", "X-CSRF-Token": "csrf" }) }));
beforeEach(() => { state.request.mockReset(); state.normalize.mockReset(); });
const input = { customerIds: ["customer-1", "customer-2"], sellerIds: ["seller-1", "seller-1", "seller-2"], effectiveFrom: "2026-08-20", reason: " Ajuste " };
test("envía asignación individual con sellerIds plural y opcionales normalizados", async () => { state.request.mockResolvedValue(new Response("{}", { status: 200 })); await expect(assignOne("customer-1", input)).resolves.toBeNull(); expect(state.request).toHaveBeenCalledWith("/customers/customer-1/assignment", expect.objectContaining({ method: "PUT", body: JSON.stringify({ sellerIds: ["seller-1", "seller-2"], effectiveFrom: "2026-08-20", reason: "Ajuste" }) }), { publishErrors: false }); });
test("envía clave idempotente y conserva rechazos parciales", async () => { state.request.mockResolvedValue(new Response(JSON.stringify({ results: [{ customerId: "customer-1", status: "ASSIGNED" }, { customerId: "customer-2", status: "REJECTED", errorCode: "CONFLICT" }] }), { status: 200 })); const result = await assignBatch(input, "intent-key"); expect(state.request).toHaveBeenCalledWith("/customer-assignments/batch", expect.objectContaining({ headers: expect.objectContaining({ "Idempotency-Key": "intent-key" }), body: JSON.stringify({ customerIds: ["customer-1", "customer-2"], sellerIds: ["seller-1", "seller-2"], effectiveFrom: "2026-08-20", reason: "Ajuste" }) }), { publishErrors: false }); expect(result.results).toEqual([{ customerId: "customer-1", status: "ASSIGNED", errorCode: null }, { customerId: "customer-2", status: "REJECTED", errorCode: "CONFLICT" }]); });
