import { apiRequest, normalizeApiError, type ApiError } from "../../lib/api";
import { getSessionAuthorization, getSessionMutationAuthorization } from "../auth/auth";
import type { AssignmentClient, AssignmentInput, AssignmentResult, AssignmentSeller, AssignmentTerritory } from "./types";

export const MAX_BATCH_CUSTOMERS = 1000;

type Page<T> = { items: readonly T[]; page: { totalPages: number } };
const page = <T,>(value: unknown, parse: (value: unknown) => T | null): Page<T> | null => {
  if (!value || typeof value !== "object") return null;
  const v = value as Record<string, unknown>; const p = v.page as Record<string, unknown> | null;
  if (!Array.isArray(v.items) || !p || typeof p.totalPages !== "number") return null;
  const items = v.items.map(parse); return items.some((item) => item === null) ? null : { items: items as T[], page: { totalPages: p.totalPages } };
};
const client = (value: unknown): AssignmentClient | null => { const v = value as Record<string, unknown>; return v && typeof v.id === "string" && typeof v.name === "string" && (v.status === "ACTIVE" || v.status === "INACTIVE") && (typeof v.territoryId === "string" || v.territoryId === null) && Array.isArray(v.assignedSellerIds) && v.assignedSellerIds.every((id) => typeof id === "string") ? { id: v.id, name: v.name, status: v.status, territoryId: v.territoryId as string | null, assignedSellerIds: v.assignedSellerIds as string[] } : null; };
const seller = (value: unknown): AssignmentSeller | null => { const v = value as Record<string, unknown>; return v && typeof v.id === "string" && typeof v.displayName === "string" && (v.status === "ACTIVE" || v.status === "INVITED" || v.status === "INACTIVE") ? { id: v.id, displayName: v.displayName, status: v.status } : null; };
const territory = (value: unknown): AssignmentTerritory | null => { const v = value as Record<string, unknown>; return v && typeof v.id === "string" && typeof v.name === "string" && (v.status === "ACTIVE" || v.status === "INACTIVE") ? { id: v.id, name: v.name, status: v.status } : null; };
async function all<T>(path: string, parser: (value: unknown) => T | null): Promise<{ response: Response; items: readonly T[] | null }> { const firstResponse = await apiRequest(`${path}${path.includes("?") ? "&" : "?"}page=0&pageSize=200`, { method: "GET", headers: getSessionAuthorization() }, { publishErrors: false }); const first = firstResponse.status === 200 ? page(await firstResponse.json().catch(() => null), parser) : null; if (!first) return { response: firstResponse, items: null }; const tail = await Promise.all(Array.from({ length: Math.max(0, first.page.totalPages - 1) }, async (_, index) => { const response = await apiRequest(`${path}${path.includes("?") ? "&" : "?"}page=${index + 1}&pageSize=200`, { method: "GET", headers: getSessionAuthorization() }, { publishErrors: false }); return { response, data: response.status === 200 ? page(await response.json().catch(() => null), parser) : null }; })); const failed = tail.find((entry) => !entry.data); return failed ? { response: failed.response, items: null } : { response: firstResponse, items: [...first.items, ...tail.flatMap((entry) => entry.data?.items ?? [])] }; }
export async function loadAssignmentOptions() { const [clients, sellers, territories] = await Promise.all([all("/customers?status=ACTIVE", client), all("/sellers?status=ACTIVE", seller), all("/territories?status=ACTIVE", territory)]); return { response: [clients, sellers, territories].find((entry) => entry.response.status !== 200)?.response ?? clients.response, clients: clients.items, sellers: sellers.items, territories: territories.items }; }
const payload = (input: AssignmentInput) => ({ sellerIds: [...new Set(input.sellerIds)], effectiveFrom: input.effectiveFrom, ...(input.reason.trim() ? { reason: input.reason.trim() } : {}) });
export async function assignOne(customerId: string, input: AssignmentInput): Promise<ApiError | null> { const response = await apiRequest(`/customers/${encodeURIComponent(customerId)}/assignment`, { method: "PUT", headers: { "Content-Type": "application/json", ...getSessionMutationAuthorization() }, body: JSON.stringify(payload(input)) }, { publishErrors: false }); return response.status >= 200 && response.status < 300 ? null : await normalizeApiError(response); }
export async function assignBatch(input: AssignmentInput, idempotencyKey: string): Promise<{ error: ApiError | null; results: readonly AssignmentResult[] }> { const customerIds = [...new Set(input.customerIds)]; if (customerIds.length > MAX_BATCH_CUSTOMERS) return { error: { status: 422, correlationId: null, fieldErrors: [{ field: "customerIds", code: "MAX_ITEMS_EXCEEDED" }] }, results: [] }; const response = await apiRequest("/customer-assignments/batch", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey, ...getSessionMutationAuthorization() }, body: JSON.stringify({ customerIds, ...payload(input) }) }, { publishErrors: false }); if (!response.ok) return { error: await normalizeApiError(response), results: [] }; const body = await response.json().catch(() => null); const values: unknown[] = body && typeof body === "object" && Array.isArray((body as Record<string, unknown>).results) ? (body as Record<string, unknown>).results as unknown[] : []; const results = values.flatMap((v): AssignmentResult[] => { const x = v as Record<string, unknown>; return typeof x?.customerId === "string" && (x.status === "ASSIGNED" || x.status === "REJECTED") ? [{ customerId: x.customerId, status: x.status, errorCode: typeof x.errorCode === "string" ? x.errorCode : null }] : []; }); return { error: null, results }; }
