package com.nahui.followupbussiness.identityaccess.adapter.in.rest;

import com.nahui.followupbussiness.identityaccess.application.port.in.LogoutSessionUseCase;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

class LogoutControllerTest {
 @Test void webPendingClearsOnlyHttpOnlyCookieAndReturnsNoContent() throws Exception {var use=mock(LogoutSessionUseCase.class);MockMvc mvc=MockMvcBuilders.standaloneSetup(new LogoutController(use,o->"https://web.test".equals(o))).build();MvcResult result=mvc.perform(post("/auth/logout").header("X-Logout-Intent","PENDING").header("Origin","https://web.test").cookie(new jakarta.servlet.http.Cookie("__Host-fs-refresh","x".repeat(43)))).andExpect(status().isNoContent()).andExpect(header().string("Cache-Control","no-store")).andExpect(header().exists("X-Correlation-Id")).andReturn();assertClearedRefreshCookie(result);var c=ArgumentCaptor.forClass(LogoutSessionUseCase.Command.class);verify(use).logout(c.capture());assertThat(c.getValue().webRefreshCookie()).hasSize(43);assertThat(c.getValue().allSessions()).isFalse();}
 @Test void mobilePendingUsesTicketWithoutBrowserAndReturnsNoContent() throws Exception {var use=mock(LogoutSessionUseCase.class);MockMvc mvc=MockMvcBuilders.standaloneSetup(new LogoutController(use,o->true)).build();mvc.perform(post("/auth/logout").header("X-Logout-Intent","PENDING").header("X-Session-Revocation-Ticket","t".repeat(43))).andExpect(status().isNoContent()).andExpect(header().string("Cache-Control","no-store")).andExpect(header().doesNotExist("Set-Cookie"));verify(use).logout(any());}
 @Test void rejectedMobileTicketReturnsNeutralProblemWithoutEchoingTicket() throws Exception {var use=mock(LogoutSessionUseCase.class);String ticket="t".repeat(43);doThrow(new com.nahui.followupbussiness.identityaccess.application.LogoutSessionService.Rejected()).when(use).logout(any());MockMvc mvc=MockMvcBuilders.standaloneSetup(new LogoutController(use,o->true)).build();mvc.perform(post("/auth/logout").header("X-Logout-Intent","PENDING").header("X-Session-Revocation-Ticket",ticket)).andExpect(status().isUnauthorized()).andExpect(header().string("Cache-Control","no-store")).andExpect(jsonPath("$.code").value("LOGOUT_INVALID")).andExpect(jsonPath("$.detail").value("Request cannot be processed")).andExpect(content().string(org.hamcrest.Matchers.not(org.hamcrest.Matchers.containsString(ticket))));verify(use).logout(any());}
 @Test void validBearerWithInvalidCsrfReturnsContractualForbiddenWithoutControllerSideEffects() throws Exception {var use=mock(LogoutSessionUseCase.class);doThrow(new com.nahui.followupbussiness.identityaccess.application.LogoutSessionService.CsrfRejected()).when(use).logout(any());var auth=mock(com.nahui.followupbussiness.identityaccess.adapter.in.security.InboundJwtAuthenticator.class);var actor=new com.nahui.followupbussiness.identityaccess.domain.model.AuthenticatedActor(UUID.randomUUID(),UUID.randomUUID(),com.nahui.followupbussiness.identityaccess.domain.model.BaseRole.SELLER,UUID.randomUUID());when(auth.authenticate("valid")).thenReturn(org.springframework.security.authentication.UsernamePasswordAuthenticationToken.authenticated(actor,"valid",java.util.List.of()));MockMvc mvc=MockMvcBuilders.standaloneSetup(new LogoutController(use,o->true)).setCustomArgumentResolvers(new org.springframework.security.web.method.annotation.AuthenticationPrincipalArgumentResolver()).addFilters(new com.nahui.followupbussiness.identityaccess.adapter.in.security.InboundJwtAuthenticationFilter(auth,new com.nahui.followupbussiness.identityaccess.adapter.in.security.RestAuthenticationEntryPoint())).build();mvc.perform(post("/auth/logout").header("Authorization","Bearer valid").header("X-CSRF-Token","invalid")).andExpect(status().isForbidden()).andExpect(header().string("Cache-Control","no-store")).andExpect(jsonPath("$.code").value("LOGOUT_INVALID"));verify(use).logout(any());}
 @Test void mixedPendingCredentialsAreNeutralAndDoNotReachUseCase() throws Exception {var use=mock(LogoutSessionUseCase.class);MockMvc mvc=MockMvcBuilders.standaloneSetup(new LogoutController(use,o->true)).build();mvc.perform(post("/auth/logout").header("X-Logout-Intent","PENDING").header("Origin","https://web.test").header("X-Session-Revocation-Ticket","t".repeat(43)).cookie(new jakarta.servlet.http.Cookie("__Host-fs-refresh","x".repeat(43)))).andExpect(status().isBadRequest()).andExpect(header().string("Cache-Control","no-store")).andExpect(jsonPath("$.code").value("LOGOUT_INVALID"));verifyNoInteractions(use);}
 @Test void normalBearerPassesInboundJwtFilterAndReachesDerivedActor() throws Exception {var use=mock(LogoutSessionUseCase.class);var auth=mock(com.nahui.followupbussiness.identityaccess.adapter.in.security.InboundJwtAuthenticator.class);var actor=new com.nahui.followupbussiness.identityaccess.domain.model.AuthenticatedActor(UUID.randomUUID(),UUID.randomUUID(),com.nahui.followupbussiness.identityaccess.domain.model.BaseRole.SELLER,UUID.randomUUID());when(auth.authenticate("valid")).thenReturn(org.springframework.security.authentication.UsernamePasswordAuthenticationToken.authenticated(actor,"valid",java.util.List.of()));MockMvc mvc=MockMvcBuilders.standaloneSetup(new LogoutController(use,o->true)).setCustomArgumentResolvers(new org.springframework.security.web.method.annotation.AuthenticationPrincipalArgumentResolver()).addFilters(new com.nahui.followupbussiness.identityaccess.adapter.in.security.InboundJwtAuthenticationFilter(auth,new com.nahui.followupbussiness.identityaccess.adapter.in.security.RestAuthenticationEntryPoint())).build();mvc.perform(post("/auth/logout").header("Authorization","Bearer valid").contentType(MediaType.APPLICATION_JSON).content("{\"allSessions\":false}")).andExpect(status().isNoContent()).andExpect(header().string("Cache-Control","no-store"));verify(use).logout(org.mockito.ArgumentMatchers.argThat(c->c.actor().equals(actor)));}
 @Test void webBearerLogoutForwardsCsrfClearsRefreshCookieAndRejectsPendingAuthorizationBeforeUseCase() throws Exception {var use=mock(LogoutSessionUseCase.class);var auth=mock(com.nahui.followupbussiness.identityaccess.adapter.in.security.InboundJwtAuthenticator.class);var actor=new com.nahui.followupbussiness.identityaccess.domain.model.AuthenticatedActor(UUID.randomUUID(),UUID.randomUUID(),com.nahui.followupbussiness.identityaccess.domain.model.BaseRole.SELLER,UUID.randomUUID());when(auth.authenticate("web")).thenReturn(org.springframework.security.authentication.UsernamePasswordAuthenticationToken.authenticated(actor,"web",java.util.List.of()));MockMvc mvc=MockMvcBuilders.standaloneSetup(new LogoutController(use,o->true)).setCustomArgumentResolvers(new org.springframework.security.web.method.annotation.AuthenticationPrincipalArgumentResolver()).addFilters(new com.nahui.followupbussiness.identityaccess.adapter.in.security.InboundJwtAuthenticationFilter(auth,new com.nahui.followupbussiness.identityaccess.adapter.in.security.RestAuthenticationEntryPoint())).build();MvcResult result=mvc.perform(post("/auth/logout").header("Authorization","Bearer web").header("X-CSRF-Token","csrf").cookie(new jakarta.servlet.http.Cookie("__Host-fs-refresh","x".repeat(43))).contentType(MediaType.APPLICATION_JSON).content("{\"allSessions\":false}")).andExpect(status().isNoContent()).andExpect(header().string("Cache-Control","no-store")).andReturn();assertClearedRefreshCookie(result);verify(use).logout(org.mockito.ArgumentMatchers.argThat(c->"csrf".equals(c.csrfToken())&&c.actor().equals(actor)));reset(use);mvc.perform(post("/auth/logout").header("X-Logout-Intent","PENDING").header("Authorization","Bearer web").header("Origin","https://web.test").cookie(new jakarta.servlet.http.Cookie("__Host-fs-refresh","x".repeat(43)))).andExpect(status().isBadRequest()).andExpect(header().doesNotExist("Set-Cookie"));verifyNoInteractions(use);}
 private static void assertClearedRefreshCookie(MvcResult result) {String cookie=result.getResponse().getHeader("Set-Cookie");assertThat(cookie).isNotBlank();String[] attributes=cookie.split(";");assertThat(attributes[0].trim()).isEqualTo("__Host-fs-refresh=");java.util.Map<String,String> values=new java.util.HashMap<>();for(int i=1;i<attributes.length;i++){String[] pair=attributes[i].trim().split("=",2);values.put(pair[0].toLowerCase(java.util.Locale.ROOT),pair.length==2?pair[1]:"");}assertThat(values).containsEntry("path","/").containsEntry("max-age","0").containsKeys("secure","httponly").doesNotContainKey("domain");assertThat(values.get("samesite")).isEqualToIgnoringCase("strict");}
}
