import { ChevronDown } from "lucide-react";
import { createPortal } from "react-dom";
import { useEffect, useId, useLayoutEffect, useRef, useState } from "react";
import "./multi-select.css";

export type MultiSelectOption = Readonly<{ value: string; label: string; disabled?: boolean }>;

export function MultiSelect({ label, ariaLabel, value, options, onChange, placeholder = "Selecciona opciones" }: { label: string; ariaLabel: string; value: readonly string[]; options: readonly MultiSelectOption[]; onChange: (value: readonly string[]) => void; placeholder?: string }) {
  const [open, setOpen] = useState(false); const [active, setActive] = useState(0); const root = useRef<HTMLDivElement>(null); const trigger = useRef<HTMLButtonElement>(null); const menu = useRef<HTMLDivElement>(null); const listboxId = useId(); const [position, setPosition] = useState({ top: 0, left: 0, width: 0 });
  const selected = options.filter(option => value.includes(option.value));
  const summary = selected.length === 0 ? placeholder : selected.length === 1 ? selected[0]?.label ?? "1 opción" : `${selected.length} opciones seleccionadas`;
  const toggle = (option: MultiSelectOption) => { if (option.disabled) return; onChange(value.includes(option.value) ? value.filter(id => id !== option.value) : [...value, option.value]); };
  const openMenu = () => { setActive(Math.max(0, options.findIndex(option => !option.disabled))); setOpen(true); };
  useEffect(() => { const close = (event: PointerEvent) => { if (event.target instanceof Node && !root.current?.contains(event.target) && !menu.current?.contains(event.target)) setOpen(false); }; document.addEventListener("pointerdown", close); return () => document.removeEventListener("pointerdown", close); }, []);
  useLayoutEffect(() => { if (!open || !trigger.current) return; const update = () => { const bounds = trigger.current?.getBoundingClientRect(); if (!bounds) return; const width = Math.max(bounds.width, 240); setPosition({ top: bounds.bottom + 6, left: Math.max(12, Math.min(bounds.left, window.innerWidth - width - 12)), width }); }; update(); window.addEventListener("resize", update); window.addEventListener("scroll", update, true); return () => { window.removeEventListener("resize", update); window.removeEventListener("scroll", update, true); }; }, [open]);
  const move = (step: 1 | -1) => { const enabled = options.flatMap((option, index) => option.disabled ? [] : [index]); if (!enabled.length) return; const index = enabled.indexOf(active); setActive(enabled[(index < 0 ? step === 1 ? 0 : enabled.length - 1 : (index + step + enabled.length) % enabled.length)] ?? 0); };
  return <div ref={root} className="filter-field multi-select"><span>{label}</span><button ref={trigger} type="button" className="multi-select__trigger" aria-label={ariaLabel} aria-haspopup="listbox" aria-controls={listboxId} aria-expanded={open} onClick={() => open ? setOpen(false) : openMenu()} onKeyDown={event => { if (event.key === "Escape") { setOpen(false); return; } if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); if (!open) openMenu(); else move(event.key === "ArrowDown" ? 1 : -1); } if ((event.key === "Enter" || event.key === " ") && !open) { event.preventDefault(); openMenu(); } }}><span className={selected.length ? "" : "multi-select__placeholder"}>{summary}</span><ChevronDown aria-hidden="true" /></button>{open && createPortal(<div ref={menu} id={listboxId} className="multi-select__menu" role="listbox" aria-label={ariaLabel} aria-multiselectable="true" style={position} onKeyDown={event => { if (event.key === "Escape") { setOpen(false); trigger.current?.focus(); } }}><div>{options.map((option, index) => <label key={option.value} role="option" aria-selected={value.includes(option.value)} data-active={index === active || undefined} onPointerMove={() => !option.disabled && setActive(index)}><input type="checkbox" checked={value.includes(option.value)} disabled={option.disabled} onChange={() => toggle(option)} /><span>{option.label}</span></label>)}</div><footer><button type="button" onClick={() => setOpen(false)}>Listo</button></footer></div>, document.body)}</div>;
}
