package com.nahui.followupbussiness.routing.application;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import com.nahui.followupbussiness.audit.application.port.in.RecordAuditEntryUseCase;
import com.nahui.followupbussiness.customers.application.port.in.CustomerPortfolioReadUseCase;
import com.nahui.followupbussiness.customers.domain.GeoPoint;
import com.nahui.followupbussiness.identityaccess.domain.model.*;
import com.nahui.followupbussiness.routing.application.port.in.CreateRouteUseCase;
import com.nahui.followupbussiness.routing.application.port.out.*;
import com.nahui.followupbussiness.routing.domain.Route;
import com.nahui.followupbussiness.tenancy.application.port.in.CurrentCompanyQuery;
import com.nahui.followupbussiness.tenancy.domain.model.*;
import com.nahui.followupbussiness.workforce.application.port.in.*;
import java.time.*;import java.util.*;import org.junit.jupiter.api.Test;
class CreateRouteServiceTest {
 @Test void rejectsNonPositiveDurationBeforeEffects(){Fixture f=new Fixture(null);assertThatThrownBy(()->f.service.create(f.command(0),f.actor)).isInstanceOf(CreateRouteUseCase.Invalid.class);verifyNoInteractions(f.routes,f.snapshots,f.matrix);}
 @Test void missingCompanyPlanningDayCreatesDraftWithoutValidSnapshot(){Fixture f=new Fixture(new CompanySettings("America/Lima","PEN",100,60,90,null));when(f.companies.findById(f.tenant)).thenReturn(Optional.of(f.company));f.stubAccess();Route route=f.service.create(f.command(60),f.actor);assertThat(route.status()).isEqualTo("DRAFT");verify(f.snapshots).saveIncomplete(eq(f.tenant),eq(route.id()),eq(1L),any());verify(f.snapshots,never()).saveValid(any());}
 @Test void incompleteMatrixCreatesDraftAndNeverValidSnapshot(){Fixture f=new Fixture(new CompanySettings("America/Lima","PEN",100,60,90,null,LocalTime.of(8,0),LocalTime.of(18,0)));UUID secondCustomer=UUID.randomUUID();when(f.companies.findById(f.tenant)).thenReturn(Optional.of(f.company));when(f.routes.reserveIdempotency(eq(f.tenant),eq(f.actorId),any(),any(),any())).thenReturn(new RouteStore.Reservation(true,null,null));when(f.sellers.allActive(f.tenant,Set.of(f.seller))).thenReturn(true);when(f.scopes.resolve(f.actor)).thenReturn(new PortfolioAccessScopeUseCase.Scope(f.tenant,true,Set.of()));when(f.customers.activeAssignedToSellerAt(eq(f.tenant),eq(f.seller),anyList(),any())).thenReturn(List.of(new CustomerPortfolioReadUseCase.RouteCustomer(f.customer,new GeoPoint(-12,-77),UUID.randomUUID()),new CustomerPortfolioReadUseCase.RouteCustomer(secondCustomer,new GeoPoint(-12.1,-77.1),UUID.randomUUID())));when(f.audit.record(any())).thenReturn(true);when(f.matrix.calculate(any())).thenReturn(new TravelMatrix.Matrix(new long[][]{{0,1},{1,0}},new long[][]{{0,1}}));Route route=f.service.create(new CreateRouteUseCase.Command(null,LocalDate.of(2026,9,1),f.seller,List.of(new CreateRouteUseCase.Visit(f.customer,60),new CreateRouteUseCase.Visit(secondCustomer,60)),UUID.randomUUID()),f.actor);verify(f.snapshots).saveIncomplete(eq(f.tenant),eq(route.id()),eq(1L),any());verify(f.snapshots,never()).saveValid(any());}
 @Test void capturesSingleVisitWithoutAnyMatrixLeg(){Fixture f=new Fixture(new CompanySettings("America/Lima","PEN",100,60,90,null,LocalTime.of(8,0),LocalTime.of(18,0)));when(f.companies.findById(f.tenant)).thenReturn(Optional.of(f.company));f.stubAccess();f.service.create(f.command(60),f.actor);verify(f.snapshots).saveValid(argThat(s->s.tenantId().equals(f.tenant)&&s.visits().getFirst().serviceSeconds()==60&&s.legs().isEmpty()&&s.shiftStart().equals(Instant.parse("2026-09-01T13:00:00Z"))));verifyNoInteractions(f.matrix);}
 @Test void capturesFiftyVisitsWithOnlyDistinctCustomerPairs(){Fixture f=new Fixture(new CompanySettings("America/Lima","PEN",100,60,90,null,LocalTime.of(8,0),LocalTime.of(18,0)));List<UUID> ids=java.util.stream.Stream.generate(UUID::randomUUID).limit(50).toList();when(f.companies.findById(f.tenant)).thenReturn(Optional.of(f.company));when(f.routes.reserveIdempotency(eq(f.tenant),eq(f.actorId),any(),any(),any())).thenReturn(new RouteStore.Reservation(true,null,null));when(f.sellers.allActive(f.tenant,Set.of(f.seller))).thenReturn(true);when(f.scopes.resolve(f.actor)).thenReturn(new PortfolioAccessScopeUseCase.Scope(f.tenant,true,Set.of()));when(f.customers.activeAssignedToSellerAt(eq(f.tenant),eq(f.seller),anyList(),any())).thenReturn(ids.stream().map(id->new CustomerPortfolioReadUseCase.RouteCustomer(id,new GeoPoint(-12,-77),UUID.randomUUID())).toList());when(f.audit.record(any())).thenReturn(true);when(f.matrix.calculate(any())).thenAnswer(i->{int n=((List<?>)i.getArgument(0)).size();long[][] v=new long[n][n];for(int x=0;x<n;x++)for(int y=0;y<n;y++)if(x!=y)v[x][y]=1;return new TravelMatrix.Matrix(v,v);});f.service.create(new CreateRouteUseCase.Command(null,LocalDate.of(2026,9,1),f.seller,ids.stream().map(id->new CreateRouteUseCase.Visit(id,60)).toList(),UUID.randomUUID()),f.actor);verify(f.matrix,times(55)).calculate(argThat(nodes->nodes.size()<=10));verify(f.snapshots).saveValid(argThat(s->s.visits().size()==50&&s.legs().size()==2450));}
 private static class Fixture {UUID tenant=UUID.randomUUID(),actorId=UUID.randomUUID(),seller=UUID.randomUUID(),customer=UUID.randomUUID();AuthenticatedActor actor=new AuthenticatedActor(actorId,tenant,BaseRole.COMPANY_ADMIN);RouteStore routes=mock(RouteStore.class);PlanningSnapshotStore snapshots=mock(PlanningSnapshotStore.class);TravelMatrix matrix=mock(TravelMatrix.class);CurrentCompanyQuery companies=mock(CurrentCompanyQuery.class);CustomerPortfolioReadUseCase customers=mock(CustomerPortfolioReadUseCase.class);SellerReferenceUseCase sellers=mock(SellerReferenceUseCase.class);PortfolioAccessScopeUseCase scopes=mock(PortfolioAccessScopeUseCase.class);RecordAuditEntryUseCase audit=mock(RecordAuditEntryUseCase.class);Company company;CreateRouteService service;Fixture(CompanySettings settings){company=settings==null?null:new Company(tenant,"c",null,"c",null,CompanyStatus.ACTIVE,settings,Instant.EPOCH,Instant.EPOCH,1);service=new CreateRouteService(routes,snapshots,matrix,companies,customers,sellers,scopes,audit,Clock.fixed(Instant.parse("2026-09-01T12:00:00Z"),ZoneOffset.UTC));}void stubAccess(){when(routes.reserveIdempotency(eq(tenant),eq(actorId),any(),any(),any())).thenReturn(new RouteStore.Reservation(true,null,null));when(sellers.allActive(tenant,Set.of(seller))).thenReturn(true);when(scopes.resolve(actor)).thenReturn(new PortfolioAccessScopeUseCase.Scope(tenant,true,Set.of()));when(customers.activeAssignedToSellerAt(eq(tenant),eq(seller),anyList(),any())).thenReturn(List.of(new CustomerPortfolioReadUseCase.RouteCustomer(customer,new GeoPoint(-12,-77),UUID.randomUUID())));when(audit.record(any())).thenReturn(true);}CreateRouteUseCase.Command command(int seconds){return new CreateRouteUseCase.Command(null,LocalDate.of(2026,9,1),seller,List.of(new CreateRouteUseCase.Visit(customer,seconds)),UUID.randomUUID());}}
}
