package com.nahui.followupbussiness.routing.application;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import com.nahui.followupbussiness.customers.application.port.in.CustomerPortfolioReadUseCase;
import com.nahui.followupbussiness.customers.domain.GeoPoint;
import com.nahui.followupbussiness.identityaccess.domain.model.*;
import com.nahui.followupbussiness.routing.application.port.in.*;
import com.nahui.followupbussiness.routing.application.port.out.*;
import com.nahui.followupbussiness.routing.domain.Route;
import com.nahui.followupbussiness.workforce.application.port.in.*;
import java.time.*; import java.util.*; import org.junit.jupiter.api.Test;

class OptimizeRouteServiceTest {
 @Test void optimizeUsesOriginalNodesOfAnAsymmetricMatrixByPriorityAndPersistsUnpublishedProposal(){
  var f=new Fixture(); f.authorize(f.admin); when(f.matrix.calculate(any())).thenReturn(new TravelMatrix.Matrix(new long[][]{{0,5,10,50},{4,0,7,13},{8,2,0,11},{3,9,6,0}},new long[][]{{0,50,100,500},{40,0,70,130},{80,20,0,110},{30,90,60,0}}));
  var result=f.service.optimize(f.command(1,9),f.admin);
  assertThat(result.orderedVisits()).extracting(OptimizeRouteUseCase.Planned::customerId).containsExactly(f.secondCustomer,f.firstCustomer);
  assertThat(result.orderedVisits()).extracting(OptimizeRouteUseCase.Planned::plannedArrivalAt).containsExactly(Instant.parse("2026-08-25T08:00:10Z"),Instant.parse("2026-08-25T08:00:13Z"));
  assertThat(result.totalTravelSeconds()).isEqualTo(25); assertThat(result.totalDistanceMeters()).isEqualTo(250); assertThat(result.totalServiceSeconds()).isEqualTo(2); assertThat(result.published()).isFalse();
  verify(f.matrix).calculate(argThat(nodes -> nodes.equals(List.of(new GeoPoint(1,1),new GeoPoint(1,1),new GeoPoint(2,2),new GeoPoint(2,2)))));
  verify(f.proposals).save(eq(f.tenant),eq(f.route),eq(f.account),eq(f.territory),argThat(saved->!saved.published()&&saved.totalTravelSeconds()==25),eq(""),eq(""));
 }
 @Test void endpointVisitsUseZeroInitialAndFinalArcsFromAnAsymmetricMatrix(){var f=new Fixture();when(f.matrix.calculate(any())).thenReturn(new TravelMatrix.Matrix(new long[][]{{0,0,10,50},{4,0,7,13},{8,2,0,0},{3,9,6,0}},new long[][]{{0,0,100,500},{40,0,70,130},{80,20,0,0},{30,90,60,0}}));var result=f.service.optimize(f.command(9,1),f.admin);assertThat(result.orderedVisits()).extracting(OptimizeRouteUseCase.Planned::customerId).containsExactly(f.firstCustomer,f.secondCustomer);assertThat(result.totalTravelSeconds()).isEqualTo(7);assertThat(result.totalDistanceMeters()).isEqualTo(70);assertThat(result.orderedVisits()).extracting(OptimizeRouteUseCase.Planned::plannedArrivalAt).containsExactly(Instant.parse("2026-08-25T08:00:00Z"),Instant.parse("2026-08-25T08:00:08Z"));verify(f.matrix).calculate(argThat(nodes -> nodes.equals(List.of(new GeoPoint(1,1),new GeoPoint(1,1),new GeoPoint(2,2),new GeoPoint(2,2)))));}
 @Test void unauthorizedRoleIsRejectedBeforeScopeOrMatrix(){var f=new Fixture(); assertThatThrownBy(()->f.service.optimize(f.command(1,2),new AuthenticatedActor(f.account,f.tenant,BaseRole.SELLER))).isInstanceOf(OptimizeRouteUseCase.Forbidden.class); verifyNoInteractions(f.scopes,f.matrix,f.routes,f.customers,f.sellers,f.proposals);}
 @Test void supervisorOutsideScopeIsRejectedBeforeMatrix(){var f=new Fixture(); when(f.scopes.resolve(f.supervisor)).thenReturn(new PortfolioAccessScopeUseCase.Scope(f.tenant,false,Set.of(UUID.randomUUID())));assertThatThrownBy(()->f.service.optimize(f.command(1,2),f.supervisor)).isInstanceOf(OptimizeRouteUseCase.Forbidden.class);verify(f.routes).find(f.tenant,f.route);verify(f.scopes).resolve(f.supervisor);verifyNoInteractions(f.matrix,f.customers,f.sellers,f.proposals);}
 @Test void availabilityEndAtStartReturnsStableValidationCodeWithoutPortInteractions(){var f=new Fixture();var valid=f.command(1,2);var invalid=new OptimizeRouteUseCase.Command(f.route,new OptimizeRouteUseCase.Window(Instant.parse("2026-08-25T09:00:00Z"),Instant.parse("2026-08-25T09:00:00Z")),1,valid.visits());assertThatThrownBy(()->f.service.optimize(invalid,f.admin)).isInstanceOf(OptimizeRouteUseCase.Invalid.class).hasMessage("AVAILABILITY_END_MUST_BE_AFTER_START");verifyNoInteractions(f.quota,f.matrix,f.routes,f.customers,f.sellers,f.proposals,f.scopes);}
 @Test void visitWindowEndAtStartReturnsStableValidationCodeWithoutPortInteractions(){var f=new Fixture();var valid=f.command(1,2);var window=new OptimizeRouteUseCase.Window(Instant.parse("2026-08-25T10:00:00Z"),Instant.parse("2026-08-25T10:00:00Z"));var invalid=new OptimizeRouteUseCase.Command(f.route,valid.availability(),1,List.of(new OptimizeRouteUseCase.Visit(f.firstCustomer,1,1,List.of(window)),valid.visits().get(1)));assertThatThrownBy(()->f.service.optimize(invalid,f.admin)).isInstanceOf(OptimizeRouteUseCase.Invalid.class).hasMessage("VISIT_WINDOW_END_MUST_BE_AFTER_START");verifyNoInteractions(f.quota,f.matrix,f.routes,f.customers,f.sellers,f.proposals,f.scopes);}
 @Test void nonPositivePriorityMapsToValidationFailureBeforeMatrix(){var f=new Fixture();assertThatThrownBy(()->f.service.optimize(f.command(0,2),f.admin)).isInstanceOf(OptimizeRouteUseCase.Invalid.class);verifyNoInteractions(f.matrix,f.routes,f.customers,f.sellers,f.proposals);}
 @Test void nullWindowsAreRejectedBeforeAnyPortInteraction(){var f=new Fixture();var invalid=new OptimizeRouteUseCase.Command(f.route,new OptimizeRouteUseCase.Window(Instant.parse("2026-08-25T08:00:00Z"),Instant.parse("2026-08-25T18:00:00Z")),1,List.of(new OptimizeRouteUseCase.Visit(f.firstCustomer,1,1,null)));assertThatThrownBy(()->f.service.optimize(invalid,f.admin)).isInstanceOf(OptimizeRouteUseCase.Invalid.class);verifyNoInteractions(f.quota,f.matrix,f.proposals,f.routes,f.customers,f.sellers,f.scopes);}
 @Test void emptyWindowsAreAcceptedAsAnUnrestrictedVisit(){var f=new Fixture();when(f.matrix.calculate(any())).thenReturn(new TravelMatrix.Matrix(new long[][]{{0,5,10,50},{4,0,7,13},{8,2,0,11},{3,9,6,0}},new long[][]{{0,50,100,500},{40,0,70,130},{80,20,0,110},{30,90,60,0}}));assertThat(f.service.optimize(f.command(1,2),f.admin).orderedVisits()).isNotEmpty();}
 @Test void unavailableMatrixMapsTo503FailureAndNeverPersists(){var f=new Fixture();f.authorize(f.admin);when(f.matrix.calculate(any())).thenThrow(new IllegalStateException());assertThatThrownBy(()->f.service.optimize(f.command(1,2),f.admin)).isInstanceOf(OptimizeRouteUseCase.Unavailable.class);verifyNoInteractions(f.proposals);}
 @Test void routeWithoutPersistedEndpointsReturnsStableValidationFailureBeforeQuotaMatrixAndPersistence(){var f=new Fixture();var command=f.command(1,2);when(f.routes.find(f.tenant,f.route)).thenReturn(Optional.of(new Route(f.route,f.tenant,"Draft",LocalDate.parse("2026-08-25"),f.seller,new GeoPoint(0,0),List.of(),Instant.EPOCH,Instant.EPOCH,1,"DRAFT")));assertThatThrownBy(()->f.service.optimize(command,f.admin)).isInstanceOf(OptimizeRouteUseCase.Invalid.class).hasMessage("ROUTE_ENDPOINT_LOCATION_REQUIRED");verifyNoInteractions(f.sellers,f.customers,f.quota,f.matrix,f.proposals);}
 @Test void firstOrLastEndpointWithoutLocationReturnsStableCodeWithoutPorts(){for(boolean firstMissing:List.of(true,false)){var f=new Fixture();var command=f.command(1,2);Route incomplete=mock(Route.class);Route.Point first=mock(Route.Point.class),last=mock(Route.Point.class);when(incomplete.sellerId()).thenReturn(f.seller);when(incomplete.status()).thenReturn("DRAFT");when(incomplete.version()).thenReturn(1L);when(incomplete.points()).thenReturn(List.of(first,last));when(first.location()).thenReturn(firstMissing?null:new GeoPoint(1,1));when(last.location()).thenReturn(firstMissing?new GeoPoint(2,2):null);when(f.routes.find(f.tenant,f.route)).thenReturn(Optional.of(incomplete));assertThatThrownBy(()->f.service.optimize(command,f.admin)).isInstanceOf(OptimizeRouteUseCase.Invalid.class).hasMessage("ROUTE_ENDPOINT_LOCATION_REQUIRED");verifyNoInteractions(f.sellers,f.customers,f.quota,f.matrix,f.proposals);}}
 @Test void exhaustedQuotaReturnsRateLimitedBeforeMatrixAndPersistence(){var f=new Fixture();var command=f.command(1,2);when(f.quota.reserve(f.tenant,f.account,LocalDate.parse("2026-08-25"))).thenReturn(false);assertThatThrownBy(()->f.service.optimize(command,f.admin)).isInstanceOf(OptimizeRouteUseCase.RateLimited.class);verify(f.quota).reserve(f.tenant,f.account,LocalDate.parse("2026-08-25"));verifyNoInteractions(f.matrix,f.proposals);}
 @Test void oneAuthorizedVisitDerivesItsTerritoryAndPersistsIt(){var f=new Fixture();var command=f.command(1,2);var oneVisit=new OptimizeRouteUseCase.Command(f.route,command.availability(),1,List.of(command.visits().getFirst()));when(f.customers.activeAssignedToSellerAt(eq(f.tenant),eq(f.seller),any(),eq(LocalDate.parse("2026-08-25")))).thenReturn(List.of(new CustomerPortfolioReadUseCase.RouteCustomer(f.firstCustomer,new GeoPoint(1,1),f.territory)));when(f.matrix.calculate(any())).thenReturn(new TravelMatrix.Matrix(new long[][]{{0,0,5},{0,0,5},{5,5,0}},new long[][]{{0,0,5},{5,5,0},{5,5,0}}));assertThat(f.service.optimize(oneVisit,f.admin).orderedVisits()).hasSize(1);verify(f.sellers).activeAssignedToTerritory(f.tenant,f.seller,f.territory);verify(f.proposals).save(eq(f.tenant),eq(f.route),eq(f.account),eq(f.territory),any(),eq(""),eq(""));}
 @Test void multipleVisitTerritoriesReturnStable422BeforeSellerQuotaMatrixAndPersistence(){var f=new Fixture(); var command=f.command(1,2); UUID other=UUID.randomUUID(); when(f.customers.activeAssignedToSellerAt(eq(f.tenant),eq(f.seller),any(),eq(LocalDate.parse("2026-08-25")))).thenReturn(List.of(new CustomerPortfolioReadUseCase.RouteCustomer(f.firstCustomer,new GeoPoint(1,1),f.territory),new CustomerPortfolioReadUseCase.RouteCustomer(f.secondCustomer,new GeoPoint(2,2),other))); assertThatThrownBy(()->f.service.optimize(command,f.admin)).isInstanceOf(OptimizeRouteUseCase.Invalid.class).hasMessage("MULTIPLE_VISIT_TERRITORIES_NOT_SUPPORTED"); verifyNoInteractions(f.sellers,f.quota,f.matrix,f.proposals); }
 @Test void visitWithoutTerritoryIsRejectedWithStableCodeBeforeSellerQuotaMatrixAndPersistence(){var f=new Fixture(); var command=f.command(1,2); when(f.customers.activeAssignedToSellerAt(eq(f.tenant),eq(f.seller),any(),eq(LocalDate.parse("2026-08-25")))).thenReturn(List.of(new CustomerPortfolioReadUseCase.RouteCustomer(f.firstCustomer,new GeoPoint(1,1),null),new CustomerPortfolioReadUseCase.RouteCustomer(f.secondCustomer,new GeoPoint(2,2),null))); assertThatThrownBy(()->f.service.optimize(command,f.admin)).isInstanceOf(OptimizeRouteUseCase.Invalid.class).hasMessage("VISIT_TERRITORY_REQUIRED"); verifyNoInteractions(f.sellers,f.quota,f.matrix,f.proposals); }
 @Test void sellerTerritoryMismatchIsValidationWithoutQuotaMatrixOrPersistence(){var f=new Fixture(); var command=f.command(1,2);when(f.sellers.activeAssignedToTerritory(f.tenant,f.seller,f.territory)).thenReturn(false); assertThatThrownBy(()->f.service.optimize(command,f.admin)).isInstanceOf(OptimizeRouteUseCase.Invalid.class).hasMessage("VISIT_TERRITORY_NOT_ASSIGNED_TO_SELLER"); verifyNoInteractions(f.quota,f.matrix,f.proposals); }
 @Test void inactiveVisitTerritoryIsRejectedBeforeQuotaMatrixAndPersistence(){var f=new Fixture(); var command=f.command(1,2);when(f.sellers.activeTerritory(f.tenant,f.territory)).thenReturn(false); assertThatThrownBy(()->f.service.optimize(command,f.admin)).isInstanceOf(OptimizeRouteUseCase.Invalid.class).hasMessage("VISIT_TERRITORY_INACTIVE"); verify(f.sellers).activeTerritory(f.tenant,f.territory); verifyNoInteractions(f.quota,f.matrix,f.proposals); verify(f.sellers,never()).activeAssignedToTerritory(f.tenant,f.seller,f.territory); }
 static final class Fixture {final UUID tenant=UUID.randomUUID(),route=UUID.randomUUID(),seller=UUID.randomUUID(),territory=UUID.randomUUID(),account=UUID.randomUUID(),firstCustomer=UUID.randomUUID(),secondCustomer=UUID.randomUUID();final AuthenticatedActor admin=new AuthenticatedActor(account,tenant,BaseRole.COMPANY_ADMIN),supervisor=new AuthenticatedActor(account,tenant,BaseRole.SUPERVISOR);final RouteStore routes=mock(RouteStore.class);final RouteProposalStore proposals=mock(RouteProposalStore.class);final TravelMatrix matrix=mock(TravelMatrix.class);final CustomerPortfolioReadUseCase customers=mock(CustomerPortfolioReadUseCase.class);final SellerReferenceUseCase sellers=mock(SellerReferenceUseCase.class);final PortfolioAccessScopeUseCase scopes=mock(PortfolioAccessScopeUseCase.class);final MatrixQuota quota=mock(MatrixQuota.class);final OptimizeRouteService service=new OptimizeRouteService(routes,proposals,matrix,customers,sellers,scopes,quota,Clock.fixed(Instant.parse("2026-08-25T12:00:00Z"),ZoneOffset.UTC));
  void authorize(AuthenticatedActor actor){when(scopes.resolve(actor)).thenReturn(new PortfolioAccessScopeUseCase.Scope(tenant,true,Set.of()));when(routes.find(tenant,route)).thenReturn(Optional.of(new Route(route,tenant,"Draft",LocalDate.parse("2026-08-25"),seller,new GeoPoint(0,0),List.of(new Route.Point(UUID.randomUUID(),firstCustomer,1,new GeoPoint(1,1)),new Route.Point(UUID.randomUUID(),secondCustomer,2,new GeoPoint(2,2))),Instant.EPOCH,Instant.EPOCH,1,"DRAFT")));when(sellers.activeTerritory(tenant,territory)).thenReturn(true);when(sellers.activeAssignedToTerritory(tenant,seller,territory)).thenReturn(true);when(customers.activeAssignedToSellerAt(eq(tenant),eq(seller),any(),eq(LocalDate.parse("2026-08-25")))).thenReturn(List.of(new CustomerPortfolioReadUseCase.RouteCustomer(firstCustomer,new GeoPoint(1,1),territory),new CustomerPortfolioReadUseCase.RouteCustomer(secondCustomer,new GeoPoint(2,2),territory)));when(quota.reserve(tenant,account,LocalDate.parse("2026-08-25"))).thenReturn(true);when(proposals.nextVersion(tenant,route)).thenReturn(3L);}
  OptimizeRouteUseCase.Command command(int first,int second){authorize(admin);return new OptimizeRouteUseCase.Command(route,new OptimizeRouteUseCase.Window(Instant.parse("2026-08-25T08:00:00Z"),Instant.parse("2026-08-25T18:00:00Z")),1,List.of(new OptimizeRouteUseCase.Visit(firstCustomer,1,first,List.of()),new OptimizeRouteUseCase.Visit(secondCustomer,1,second,List.of())));}
 }
}
