package com.nahui.followupbussiness.routing.application;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import com.nahui.followupbussiness.customers.application.port.in.CustomerPortfolioReadUseCase;
import com.nahui.followupbussiness.customers.domain.GeoPoint;
import com.nahui.followupbussiness.identityaccess.domain.model.*;
import com.nahui.followupbussiness.routing.application.port.in.*;
import com.nahui.followupbussiness.routing.application.port.out.*;
import com.nahui.followupbussiness.routing.domain.Route;
import com.nahui.followupbussiness.workforce.application.port.in.*;
import java.time.*; import java.util.*; import org.junit.jupiter.api.Test;

class OptimizeRouteServiceTest {
 @Test void optimizeUsesOriginalNodesOfAnAsymmetricMatrixByPriorityAndPersistsUnpublishedProposal(){
  var f=new Fixture(); f.authorize(f.admin); when(f.matrix.calculate(any())).thenReturn(new TravelMatrix.Matrix(new long[][]{{0,5,10,50},{4,0,7,13},{8,2,0,11},{3,9,6,0}},new long[][]{{0,50,100,500},{40,0,70,130},{80,20,0,110},{30,90,60,0}}));
  var result=f.service.optimize(f.command(1,9),f.admin);
  assertThat(result.orderedVisits()).extracting(OptimizeRouteUseCase.Planned::customerId).containsExactly(f.secondCustomer,f.firstCustomer);
  assertThat(result.orderedVisits()).extracting(OptimizeRouteUseCase.Planned::plannedArrivalAt).containsExactly(Instant.parse("2026-08-25T08:00:10Z"),Instant.parse("2026-08-25T08:00:13Z"));
  assertThat(result.totalTravelSeconds()).isEqualTo(25); assertThat(result.totalDistanceMeters()).isEqualTo(250); assertThat(result.totalServiceSeconds()).isEqualTo(2); assertThat(result.published()).isFalse();
  verify(f.proposals).save(eq(f.tenant),eq(f.route),eq(f.account),eq(f.territory),argThat(saved->!saved.published()&&saved.totalTravelSeconds()==25),eq(""),eq(""));
 }
 @Test void unauthorizedRoleIsRejectedBeforeScopeOrMatrix(){var f=new Fixture(); assertThatThrownBy(()->f.service.optimize(f.command(1,2),new AuthenticatedActor(f.account,f.tenant,BaseRole.SELLER))).isInstanceOf(OptimizeRouteUseCase.Forbidden.class); verifyNoInteractions(f.scopes,f.matrix,f.routes,f.customers,f.sellers,f.proposals);}
 @Test void supervisorOutsideScopeIsRejectedBeforeMatrix(){var f=new Fixture(); when(f.scopes.resolve(f.supervisor)).thenReturn(new PortfolioAccessScopeUseCase.Scope(f.tenant,false,Set.of(UUID.randomUUID())));assertThatThrownBy(()->f.service.optimize(f.command(1,2),f.supervisor)).isInstanceOf(OptimizeRouteUseCase.Forbidden.class);verify(f.scopes).resolve(f.supervisor);verifyNoInteractions(f.matrix,f.routes,f.customers,f.sellers,f.proposals);}
 @Test void invalidRequestMapsToValidationFailureBeforeMatrix(){var f=new Fixture();var invalid=new OptimizeRouteUseCase.Command(f.route,LocalDate.parse("2026-08-25"),f.seller,f.territory,new GeoPoint(0,0),new GeoPoint(3,3),new OptimizeRouteUseCase.Window(Instant.parse("2026-08-25T09:00:00Z"),Instant.parse("2026-08-25T08:00:00Z")),1,List.of());assertThatThrownBy(()->f.service.optimize(invalid,f.admin)).isInstanceOf(OptimizeRouteUseCase.Invalid.class);verifyNoInteractions(f.matrix,f.routes,f.customers,f.sellers,f.proposals);}
 @Test void nonPositivePriorityMapsToValidationFailureBeforeMatrix(){var f=new Fixture();assertThatThrownBy(()->f.service.optimize(f.command(0,2),f.admin)).isInstanceOf(OptimizeRouteUseCase.Invalid.class);verifyNoInteractions(f.matrix,f.routes,f.customers,f.sellers,f.proposals);}
 @Test void unavailableMatrixMapsTo503FailureAndNeverPersists(){var f=new Fixture();f.authorize(f.admin);when(f.matrix.calculate(any())).thenThrow(new IllegalStateException());assertThatThrownBy(()->f.service.optimize(f.command(1,2),f.admin)).isInstanceOf(OptimizeRouteUseCase.Unavailable.class);verifyNoInteractions(f.proposals);}
 @Test void routeSellerMismatchIsDeniedBeforeQuotaMatrixAndPersistence(){var f=new Fixture();var command=f.command(1,2);when(f.routes.find(f.tenant,f.route)).thenReturn(Optional.of(new Route(f.route,f.tenant,"Draft",LocalDate.parse("2026-08-25"),UUID.randomUUID(),new GeoPoint(0,0),List.of(new Route.Point(UUID.randomUUID(),f.firstCustomer,1,new GeoPoint(1,1))),Instant.EPOCH,Instant.EPOCH,1,"DRAFT")));assertThatThrownBy(()->f.service.optimize(command,f.admin)).isInstanceOf(OptimizeRouteUseCase.Forbidden.class);verifyNoInteractions(f.quota,f.matrix,f.proposals);}
 @Test void routeDateMismatchIsDeniedBeforeQuotaMatrixAndPersistence(){var f=new Fixture();var command=f.command(1,2);when(f.routes.find(f.tenant,f.route)).thenReturn(Optional.of(new Route(f.route,f.tenant,"Draft",LocalDate.parse("2026-08-26"),f.seller,new GeoPoint(0,0),List.of(new Route.Point(UUID.randomUUID(),f.firstCustomer,1,new GeoPoint(1,1))),Instant.EPOCH,Instant.EPOCH,1,"DRAFT")));assertThatThrownBy(()->f.service.optimize(command,f.admin)).isInstanceOf(OptimizeRouteUseCase.Forbidden.class);verifyNoInteractions(f.quota,f.matrix,f.proposals);}
 @Test void exhaustedQuotaReturnsRateLimitedBeforeMatrixAndPersistence(){var f=new Fixture();var command=f.command(1,2);when(f.quota.reserve(f.tenant,f.account,LocalDate.parse("2026-08-25"))).thenReturn(false);assertThatThrownBy(()->f.service.optimize(command,f.admin)).isInstanceOf(OptimizeRouteUseCase.RateLimited.class);verify(f.quota).reserve(f.tenant,f.account,LocalDate.parse("2026-08-25"));verifyNoInteractions(f.matrix,f.proposals);}
 static final class Fixture {final UUID tenant=UUID.randomUUID(),route=UUID.randomUUID(),seller=UUID.randomUUID(),territory=UUID.randomUUID(),account=UUID.randomUUID(),firstCustomer=UUID.randomUUID(),secondCustomer=UUID.randomUUID();final AuthenticatedActor admin=new AuthenticatedActor(account,tenant,BaseRole.COMPANY_ADMIN),supervisor=new AuthenticatedActor(account,tenant,BaseRole.SUPERVISOR);final RouteStore routes=mock(RouteStore.class);final RouteProposalStore proposals=mock(RouteProposalStore.class);final TravelMatrix matrix=mock(TravelMatrix.class);final CustomerPortfolioReadUseCase customers=mock(CustomerPortfolioReadUseCase.class);final SellerReferenceUseCase sellers=mock(SellerReferenceUseCase.class);final PortfolioAccessScopeUseCase scopes=mock(PortfolioAccessScopeUseCase.class);final MatrixQuota quota=mock(MatrixQuota.class);final OptimizeRouteService service=new OptimizeRouteService(routes,proposals,matrix,customers,sellers,scopes,quota,Clock.fixed(Instant.parse("2026-08-25T12:00:00Z"),ZoneOffset.UTC));
  void authorize(AuthenticatedActor actor){when(scopes.resolve(actor)).thenReturn(new PortfolioAccessScopeUseCase.Scope(tenant,true,Set.of()));when(routes.find(tenant,route)).thenReturn(Optional.of(new Route(route,tenant,"Draft",LocalDate.parse("2026-08-25"),seller,new GeoPoint(0,0),List.of(new Route.Point(UUID.randomUUID(),firstCustomer,1,new GeoPoint(1,1))),Instant.EPOCH,Instant.EPOCH,1,"DRAFT")));when(sellers.activeAssignedToTerritory(tenant,seller,territory)).thenReturn(true);when(customers.activeAssignedToSellerAt(eq(tenant),eq(seller),any(),eq(LocalDate.parse("2026-08-25")))).thenReturn(List.of(new CustomerPortfolioReadUseCase.RouteCustomer(firstCustomer,new GeoPoint(1,1),territory),new CustomerPortfolioReadUseCase.RouteCustomer(secondCustomer,new GeoPoint(2,2),territory)));when(quota.reserve(tenant,account,LocalDate.parse("2026-08-25"))).thenReturn(true);when(proposals.nextVersion(tenant,route)).thenReturn(3L);}
  OptimizeRouteUseCase.Command command(int first,int second){authorize(admin);return new OptimizeRouteUseCase.Command(route,LocalDate.parse("2026-08-25"),seller,territory,new GeoPoint(0,0),new GeoPoint(3,3),new OptimizeRouteUseCase.Window(Instant.parse("2026-08-25T08:00:00Z"),Instant.parse("2026-08-25T18:00:00Z")),1,List.of(new OptimizeRouteUseCase.Visit(firstCustomer,1,first,List.of()),new OptimizeRouteUseCase.Visit(secondCustomer,1,second,List.of())));}
 }
}
