import { useEffect, useRef, useState } from "react";
import { ApiRequestObsoleteError, normalizeApiError, type ApiError } from "../../../lib/api";
import { getSessionGeneration, getSessionIdentity, subscribeToSession } from "../../auth/auth";
import { assignBatch, assignOne, loadAssignmentOptions } from "../api";
import type { AssignmentClient, AssignmentInput, AssignmentResult, AssignmentSeller, AssignmentTerritory } from "../types";
const key = () => { const i = getSessionIdentity(); return `${getSessionGeneration()}:${i?.id ?? ""}:${JSON.stringify(i?.company ?? null)}`; };
export function useCustomerAssignments() { const [clients, setClients] = useState<readonly AssignmentClient[]>([]), [sellers, setSellers] = useState<readonly AssignmentSeller[]>([]), [territories, setTerritories] = useState<readonly AssignmentTerritory[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState<ApiError | null>(null), [lastUpdated, setLastUpdated] = useState<Date | null>(null), [results, setResults] = useState<readonly AssignmentResult[]>([]); const request = useRef(0), currentKey = useRef(key());
 const reset = () => { request.current++; setClients([]); setSellers([]); setTerritories([]); setError(null); setResults([]); setLastUpdated(null); setLoading(false); };
 const reload = () => { const id = ++request.current; setLoading(true); void loadAssignmentOptions().then(async data => { if (id !== request.current) return; if (data.clients && data.sellers && data.territories) { setClients(data.clients); setSellers(data.sellers); setTerritories(data.territories); setError(null); setLastUpdated(new Date()); } else setError((await normalizeApiError(data.response)) ?? { status: 500, correlationId: null, fieldErrors: [] }); }).catch(reason => { if (id === request.current && !(reason instanceof ApiRequestObsoleteError)) setError({ status: 500, correlationId: null, fieldErrors: [] }); }).finally(() => { if (id === request.current) setLoading(false); }); };
 useEffect(() => { queueMicrotask(reload); return subscribeToSession(() => { const next = key(); if (next !== currentKey.current) { currentKey.current = next; reset(); } }); }, []);
 const submit = async (input: AssignmentInput, intentKey: string) => { const submissionKey = currentKey.current; setError(null); let next: readonly AssignmentResult[] = []; const customerId = input.customerIds[0]; const outcome = input.customerIds.length === 1 && customerId !== undefined ? await assignOne(customerId, input) : await (async () => { const batch = await assignBatch(input, intentKey); next = batch.results; return batch.error; })(); if (submissionKey !== currentKey.current || submissionKey !== key()) return false; if (outcome) { setError(outcome); return false; } setResults(next.length ? next : input.customerIds.map(customerId => ({ customerId, status: "ASSIGNED" as const, errorCode: null }))); reload(); return true; };
 return { clients, sellers, territories, loading, error, lastUpdated, results, reload, submit, clearResults: () => setResults([]) }; }
