import { useEffect, useMemo, useRef, useState } from "react";
import { AsyncStateCard } from "../../../shared/ui/AsyncStateCard";
import { ConfirmationDialog } from "../../../shared/ui/ConfirmationDialog";
import { DataTable, DataTableStatus } from "../../../shared/ui/DataTable";
import { DateFilterField } from "../../../shared/ui/DateFilterField";
import { InlineAlert } from "../../../shared/ui/error-ui/components";
import { ModalHeader } from "../../../shared/ui/ModalHeader";
import { ModalSurface } from "../../../shared/ui/ModalSurface";
import { MultiSelect } from "../../../shared/ui/MultiSelect";
import { TableLoadingIndicator } from "../../../shared/ui/TableLoadingIndicator";
import { VisualSelect } from "../../../shared/ui/VisualSelect";
import { getSessionIdentity, subscribeToSession } from "../../auth/auth";
import { useCustomerAssignments } from "../hooks/useCustomerAssignments";
import type { AssignmentInput, AssignmentResult } from "../types";
import "../styles/customer-assignments.css";

export function CustomerAssignmentPage() {
 const data = useCustomerAssignments(); const [selected, setSelected] = useState<readonly string[]>([]), [sellerIds, setSellerIds] = useState<readonly string[]>([]), [query, setQuery] = useState(""), [territory, setTerritory] = useState(""), [effectiveFrom, setEffectiveFrom] = useState(""), [reason, setReason] = useState(""), [confirming, setConfirming] = useState(false), [busy, setBusy] = useState(false); const key = useRef(""); const intentKey = useRef<string | null>(null);
 const admin = getSessionIdentity()?.roles.includes("COMPANY_ADMIN") ?? false;
 useEffect(() => subscribeToSession(() => { const next = `${getSessionIdentity()?.id ?? ""}:${JSON.stringify(getSessionIdentity()?.company ?? null)}`; if (next !== key.current) { key.current = next; setSelected([]); setSellerIds([]); setQuery(""); setTerritory(""); setEffectiveFrom(""); setReason(""); setConfirming(false); setBusy(false); } }), []);
 const visible = useMemo(() => data.clients.filter(c => c.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()) && (!territory || c.territoryId === territory)), [data.clients, query, territory]);
 const labels = new Map(data.sellers.map(s => [s.id, s.displayName])); const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]);
 const valid = selected.length > 0 && sellerIds.length > 0 && effectiveFrom.length > 0;
 const submit = async () => { if (!valid) return; setBusy(true); const input: AssignmentInput = { customerIds: selected, sellerIds, effectiveFrom, reason }; const ok = await data.submit(input, intentKey.current ??= crypto.randomUUID()); setBusy(false); if (ok) { intentKey.current = null; setConfirming(false); setSelected([]); setSellerIds([]); setReason(""); } };
 if (!admin) return <AsyncStateCard tone="error" title="No tienes permisos" description="No tienes permiso para asignar cartera de clientes." />;
 return <section className="customer-assignment" aria-labelledby="customer-assignment-title"><header><div><h1 id="customer-assignment-title">Asignar cartera</h1><p>Asigna clientes activos a uno o más vendedores activos.</p></div></header>
 {data.error && <InlineAlert variant={data.error.status === 409 ? "warning" : "error"} title={data.error.status === 403 ? "No tienes permisos" : data.error.status === 404 ? "El recurso ya no existe" : data.error.status === 409 ? "La información cambió" : data.error.status === 422 ? "Revisa la asignación" : "No pudimos completar la operación"} message={data.error.status === 409 || data.error.status === 422 ? "Conservamos tu selección para que la revises." : "Los datos mostrados pueden no estar vigentes."} action={{ label: "Reintentar", onClick: data.reload }} />}
 {data.loading && data.clients.length === 0 ? <TableLoadingIndicator label="Cargando cartera" /> : <div className="customer-assignment__panels"><section className="customer-assignment__panel"><div className="customer-assignment__filters"><label><span>Buscar clientes</span><input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar por nombre" /></label><VisualSelect ariaLabel="Filtrar por zona" value={territory || "ALL"} options={[{ value: "ALL", label: "Todas las zonas" }, ...data.territories.map(t => ({ value: t.id, label: t.name }))]} onChange={value => setTerritory(value === "ALL" ? "" : value)} /></div>{visible.length === 0 ? <AsyncStateCard title={query || territory ? "No encontramos clientes" : "Aún no hay clientes activos"} description="Prueba con otros filtros." /> : <DataTable ariaLabel="Clientes activos para asignar" items={visible} rowKey={c => c.id} columns={[{ id: "select", header: <span className="sr-only">Seleccionar</span>, label: "Seleccionar", render: c => <input type="checkbox" aria-label={`Seleccionar ${c.name}`} checked={selected.includes(c.id)} onChange={() => toggle(c.id)} /> }, { id: "name", header: "Cliente", label: "Cliente", render: c => c.name }, { id: "current", header: "Responsables actuales", label: "Responsables actuales", render: c => c.assignedSellerIds.length ? c.assignedSellerIds.map(id => labels.get(id) ?? "Responsable no disponible").join(", ") : "Sin asignar" }]} />}</section>
 <aside className="customer-assignment__panel customer-assignment__form" aria-label="Nueva asignación"><h2>Responsables y vigencia</h2><MultiSelect label="Vendedores activos" ariaLabel="Vendedores activos" value={sellerIds} options={data.sellers.filter(s => s.status === "ACTIVE").map(s => ({ value: s.id, label: s.displayName }))} onChange={value => { intentKey.current = null; setSellerIds(value); }} /><DateFilterField label="Vigente desde" value={effectiveFrom} onValueChange={value => { intentKey.current = null; setEffectiveFrom(value); }} /><label>Motivo (opcional)<textarea value={reason} maxLength={500} onChange={e => { intentKey.current = null; setReason(e.target.value); }} /></label><p className="customer-assignment__warning">La asignación puede afectar rutas ya publicadas.</p><button type="button" className="customer-assignment__submit" disabled={!valid || busy} onClick={() => { intentKey.current = crypto.randomUUID(); setConfirming(true); }}>Revisar asignación ({selected.length})</button></aside></div>}
 {data.results.length > 0 && <CustomerAssignmentResultDialog results={data.results} customerNames={new Map(data.clients.map(client => [client.id, client.name]))} onClose={data.clearResults} />}
 {confirming && <ConfirmationDialog titleId="customer-assignment-confirm" title="Confirmar asignación" message={`Asignarás ${selected.length} cliente(s) a ${sellerIds.map(id => labels.get(id) ?? "Responsable no disponible").join(", ")}. Las rutas publicadas podrían verse afectadas.`} confirmLabel="Confirmar asignación" busy={busy} busyLabel="Asignando…" onCancel={() => !busy && setConfirming(false)} onConfirm={() => void submit()} />}</section>;
}

function CustomerAssignmentResultDialog({ results, customerNames, onClose }: { results: readonly AssignmentResult[]; customerNames: ReadonlyMap<string, string>; onClose: () => void }) {
 const assigned = results.filter(result => result.status === "ASSIGNED").length; const rejected = results.length - assigned;
 return <ModalSurface titleId="customer-assignment-results-title" onDismiss={onClose} className="customer-assignment__results-dialog"><ModalHeader module="CARTERA" title="Resultado de la asignación" titleId="customer-assignment-results-title" description={`${assigned} asignado${assigned === 1 ? "" : "s"}${rejected ? ` · ${rejected} rechazado${rejected === 1 ? "" : "s"}` : ""}.`} onClose={onClose} closeLabel="Cerrar resultados" /><div className="customer-assignment__results-list" aria-live="polite">{results.map(result => <article key={result.customerId}><div><strong>{customerNames.get(result.customerId) ?? "Cliente"}</strong>{result.errorCode && <span>No se pudo completar la asignación.</span>}</div><DataTableStatus tone={result.status === "ASSIGNED" ? "success" : "danger"} label={result.status === "ASSIGNED" ? "Asignado" : "Rechazado"} /></article>)}</div><footer><button type="button" className="operation-dialog__primary" onClick={onClose}>Cerrar</button></footer></ModalSurface>;
}
