package com.nahui.followupbussiness.identityaccess.config;
import com.nahui.followupbussiness.identityaccess.adapter.in.rest.LoginRateLimiter; import com.nahui.followupbussiness.identityaccess.adapter.in.rest.LoginRequestSizeFilter; import com.nahui.followupbussiness.identityaccess.adapter.out.persistence.*; import com.nahui.followupbussiness.identityaccess.adapter.out.security.*; import com.nahui.followupbussiness.identityaccess.application.*; import com.nahui.followupbussiness.identityaccess.application.port.out.*; import com.nahui.followupbussiness.tenancy.application.port.in.CompanyAccessStatusQuery;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.boot.context.properties.EnableConfigurationProperties; import org.springframework.context.annotation.*; import org.springframework.jdbc.core.JdbcTemplate; import java.nio.charset.StandardCharsets; import java.security.*; import java.security.spec.*; import java.time.Clock; import java.util.Base64;
@Configuration(proxyBeanMethods=false) @ConditionalOnProperty(prefix="field-sales.authentication",name="rs256-private-key") @EnableConfigurationProperties(AuthenticationProperties.Values.class) public class LoginConfiguration {
 @Bean LoginService loginService(JdbcTemplate j,CompanyAccessStatusQuery c,AuthenticationProperties.Values p){try{if(p.getKid()==null||p.getKid().isBlank()||p.getIssuer()==null||p.getIssuer().isBlank()||p.getAudience()==null||p.getAudience().isBlank()||p.getWebOrigin()==null||p.getWebOrigin().isBlank()||p.getHmacSecret()==null||p.getHmacSecret().length()<32) throw new IllegalStateException("Authentication signing configuration is incomplete"); PrivateKey k=KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(Base64.getDecoder().decode(p.getRs256PrivateKey()))); if(!"RSA".equals(k.getAlgorithm())) throw new IllegalStateException("Authentication key must be RSA"); return new LoginService(new JdbcLoginAccountQuery(j),new BCryptPasswordHashingAdapter(),c,new JdbcSessionFamilyAdapter(j),new Rs256AccessTokenAdapter(k,p.getKid(),p.getIssuer(),p.getAudience(),Clock.systemUTC()),Clock.systemUTC(),p.getHmacSecret().getBytes(StandardCharsets.UTF_8));}catch(IllegalArgumentException|GeneralSecurityException e){throw new IllegalStateException("Invalid RS256 authentication key",e);}}
 @Bean LoginRateLimiter loginRateLimiter(StringRedisTemplate redis, AuthenticationProperties.Values p){return new LoginRateLimiter(redis,p.getHmacSecret().getBytes(StandardCharsets.UTF_8));}
 @Bean LoginRequestSizeFilter loginRequestSizeFilter(){return new LoginRequestSizeFilter();}
}
