package com.nahui.followupbussiness.identityaccess.application;

import com.nahui.followupbussiness.audit.application.RecordAuthenticationAuditCommand;
import com.nahui.followupbussiness.audit.application.port.in.RecordAuthenticationAuditUseCase;
import com.nahui.followupbussiness.identityaccess.application.port.in.LogoutSessionUseCase;
import com.nahui.followupbussiness.identityaccess.application.port.out.RefreshSessionPort;
import com.nahui.followupbussiness.identityaccess.domain.model.AuthenticatedActor;
import com.nahui.followupbussiness.identityaccess.domain.model.BaseRole;
import java.time.*; import java.util.*;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.*;

class LogoutSessionServiceTest {
    private final UUID account=UUID.randomUUID(), tenant=UUID.randomUUID(), family=UUID.randomUUID(); private final Instant now=Instant.parse("2026-08-04T12:00:00Z");
    @Test void currentLogoutRevokesOnlyAuthenticatedFamilyAndAuditsSanitizedContext(){var sessions=new Sessions(current("WEB")); var audit=new Audit(); service(sessions,audit).logout(new LogoutSessionUseCase.Command(new AuthenticatedActor(account,tenant,BaseRole.SELLER,family),false,"csrf",null,null,UUID.randomUUID())); assertThat(sessions.revoked).containsExactly(family); assertThat(sessions.global).isFalse(); assertThat(audit.commands).singleElement().extracting(RecordAuthenticationAuditCommand::result).isEqualTo(RecordAuthenticationAuditCommand.Result.LOGGED_OUT);}
    @Test void globalLogoutUsesOnlyAuthenticatedAccountAndTenant(){var sessions=new Sessions(current("MOBILE")); service(sessions,new Audit()).logout(new LogoutSessionUseCase.Command(new AuthenticatedActor(account,tenant,BaseRole.SELLER,family),true,null,null,null,UUID.randomUUID())); assertThat(sessions.global).isTrue(); assertThat(sessions.globalAccount).isEqualTo(account); assertThat(sessions.globalTenant).isEqualTo(tenant);}
    @Test void pendingMobileTicketIsConsumedAndReplayIsRejectedWithoutAnotherAudit(){var sessions=new Sessions(current("MOBILE")); var audit=new Audit(); service(sessions,audit).logout(new LogoutSessionUseCase.Command(null,false,null,"ticket",null,UUID.randomUUID())); assertThatThrownBy(()->service(sessions,audit).logout(new LogoutSessionUseCase.Command(null,false,null,"ticket",null,UUID.randomUUID()))).isInstanceOf(LogoutSessionService.Rejected.class); assertThat(sessions.revoked).containsExactly(family); assertThat(audit.commands).singleElement().extracting(RecordAuthenticationAuditCommand::result).isEqualTo(RecordAuthenticationAuditCommand.Result.LOGGED_OUT);}
    @Test void webActorWithoutValidCsrfAndCrossTenantFamilyAreRejected(){var sessions=new Sessions(current("WEB")); var audit=new Audit(); assertThatThrownBy(()->service(sessions,audit).logout(new LogoutSessionUseCase.Command(new AuthenticatedActor(account,UUID.randomUUID(),BaseRole.SELLER,family),false,"csrf",null,null,UUID.randomUUID()))).isInstanceOf(LogoutSessionService.Rejected.class); assertThatThrownBy(()->service(sessions,audit).logout(new LogoutSessionUseCase.Command(new AuthenticatedActor(account,tenant,BaseRole.SELLER,family),false,"wrong",null,null,UUID.randomUUID()))).isInstanceOf(LogoutSessionService.Rejected.class); assertThat(sessions.revoked).isEmpty(); assertThat(audit.commands).singleElement().extracting(RecordAuthenticationAuditCommand::reason).isEqualTo(RecordAuthenticationAuditCommand.Reason.CSRF_INVALID);}
    @Test void unavailableAbuseMonitorNeverPreventsDurableRevocation(){var sessions=new Sessions(current("MOBILE")); var s=new LogoutSessionService(sessions,new Audit(),(a,t)->{throw new IllegalStateException("redis down");},Clock.fixed(now,ZoneOffset.UTC),"01234567890123456789012345678901".getBytes()); s.logout(new LogoutSessionUseCase.Command(new AuthenticatedActor(account,tenant,BaseRole.SELLER,family),false,null,null,null,UUID.randomUUID())); assertThat(sessions.revoked).containsExactly(family);}
    @Test void unavailableAuditFailsClosed(){var sessions=new Sessions(current("MOBILE")); var s=new LogoutSessionService(sessions,c->{throw new IllegalStateException("audit down");},Clock.fixed(now,ZoneOffset.UTC),"01234567890123456789012345678901".getBytes()); assertThatThrownBy(()->s.logout(new LogoutSessionUseCase.Command(new AuthenticatedActor(account,tenant,BaseRole.SELLER,family),false,null,null,null,UUID.randomUUID()))).isInstanceOf(IllegalStateException.class);}
    @Test void expiredMobilePendingTicketIsRejectedWithoutRevocation(){var sessions=new Sessions(new RefreshSessionPort.Resolution(family,account,tenant,"MOBILE",null,null,now,null,null,true)); assertThatThrownBy(()->service(sessions,new Audit()).logout(new LogoutSessionUseCase.Command(null,false,null,"ticket",null,UUID.randomUUID()))).isInstanceOf(LogoutSessionService.Rejected.class); assertThat(sessions.revoked).isEmpty();}
    @Test void currentAndMobilePendingPassOnlyDerivedTechnicalIdsToInstallationPort(){var sessions=new Sessions(current("MOBILE"));var calls=new ArrayList<String>();var s=new LogoutSessionService(sessions,new Audit(),(a,t)->new com.nahui.followupbussiness.identityaccess.application.port.out.LogoutAbuseMonitor.Decision(false,0),(f,t)->calls.add(f+":"+t),Clock.fixed(now,ZoneOffset.UTC),"01234567890123456789012345678901".getBytes());s.logout(new LogoutSessionUseCase.Command(new AuthenticatedActor(account,tenant,BaseRole.SELLER,family),false,null,null,null,UUID.randomUUID()));s.logout(new LogoutSessionUseCase.Command(null,false,null,"ticket",null,UUID.randomUUID()));assertThat(calls).containsExactly(family+":"+tenant,family+":"+tenant);}
    @Test void mobileReplayHasNeutralRejectionAndDoesNotRepeatInstallationRevocation(){var sessions=new Sessions(current("MOBILE"));var calls=new ArrayList<String>();var s=new LogoutSessionService(sessions,new Audit(),(a,t)->new com.nahui.followupbussiness.identityaccess.application.port.out.LogoutAbuseMonitor.Decision(false,0),(f,t)->calls.add(f+":"+t),Clock.fixed(now,ZoneOffset.UTC),"01234567890123456789012345678901".getBytes());s.logout(new LogoutSessionUseCase.Command(null,false,null,"ticket",null,UUID.randomUUID()));assertThatThrownBy(()->s.logout(new LogoutSessionUseCase.Command(null,false,null,"ticket",null,UUID.randomUUID()))).isInstanceOf(LogoutSessionService.Rejected.class).hasNoCause().hasMessage(null);assertThat(calls).containsExactly(family+":"+tenant);}
    private LogoutSessionService service(Sessions s,Audit a){return new LogoutSessionService(s,a,Clock.fixed(now,ZoneOffset.UTC),"01234567890123456789012345678901".getBytes());}
    private RefreshSessionPort.Resolution current(String channel){return new RefreshSessionPort.Resolution(family,account,tenant,channel,null,channel.equals("WEB")?hmac("csrf"):null,now.plusSeconds(60),null,null,true);}
    private byte[] hmac(String value){try{var mac=javax.crypto.Mac.getInstance("HmacSHA256");mac.init(new javax.crypto.spec.SecretKeySpec("01234567890123456789012345678901".getBytes(),"HmacSHA256"));return mac.doFinal(value.getBytes());}catch(Exception e){throw new AssertionError(e);}}
    private final class Sessions implements RefreshSessionPort { final RefreshSessionPort.Resolution r; final List<UUID> revoked=new ArrayList<>(); boolean global,ticketConsumed; UUID globalAccount,globalTenant; Sessions(RefreshSessionPort.Resolution r){this.r=r;} public Resolution resolve(byte[] d){return r;} public Rotation rotate(Resolution a,byte[]b,byte[]c,byte[]d,Instant e){return null;} public void revoke(UUID id,Instant n){revoked.add(id);} public void revokeAll(UUID a,UUID t,Instant n){global=true;globalAccount=a;globalTenant=t;} public Resolution consumeRevocationTicket(byte[] d,Instant n){if(ticketConsumed)return null;ticketConsumed=true;return r;} public Resolution resolveById(UUID i,UUID a,UUID t){return family.equals(i)&&account.equals(a)&&tenant.equals(t)?r:null;} public List<UUID> activeFamilyIds(UUID a,UUID t){return List.of(family);} }
    private static final class Audit implements RecordAuthenticationAuditUseCase { final List<RecordAuthenticationAuditCommand> commands=new ArrayList<>(); public void record(RecordAuthenticationAuditCommand c){commands.add(c);} }
}
