package com.nahui.followupbussiness.identityaccess.application;

import static org.assertj.core.api.Assertions.*;
import com.nahui.followupbussiness.identityaccess.application.port.out.*;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.Test;

class PasswordRecoveryServiceTest {
    private final UUID account=UUID.randomUUID(), tenant=UUID.randomUUID();
    @Test void requestIsNeutralAndCreatesOpaqueLatestWinsResetForActiveAccount(){ var store=new Store("ACTIVE"); var s=service(store); s.request("person@example.test"); assertThat(store.notificationToken).hasSize(43); assertThat(store.token.digest()).isNotEqualTo(store.notificationToken.getBytes()); assertThat(store.token.purpose()).isEqualTo(PasswordRecoveryPort.Purpose.PASSWORD_RESET); assertThat(store.token.expiresAt()).isEqualTo(Instant.parse("2026-01-01T00:30:00Z")); s.request("missing@example.test"); assertThat(store.replacements).isEqualTo(1); }
    @Test void acceptancePersistsOnlyGenericRequestWithoutResolvingAccountOrIssuingToken(){ var store=new Store("ACTIVE"); service(store).accept("person@example.test"); assertThat(store.accepted).isEqualTo("person@example.test"); assertThat(store.replacements).isZero(); assertThat(store.notificationToken).isNull(); }
    @Test void invitedAccountActivatesWithoutChangingTenantOrRoleAndRevokesAllSessions(){ var store=new Store("INVITED"); var s=service(store); s.request("person@example.test"); store.consume=store.token; s.reset(store.notificationToken,"Valid123".toCharArray()); assertThat(store.activation).isTrue(); assertThat(store.resetTenant).isEqualTo(tenant); assertThat(store.invalidated).isEqualTo(account); assertThat(store.sessions.revoked).containsExactly(account,tenant); }
    @Test void invalidExpiredAndWeakPasswordsAreRejectedWithoutMutatingAccount(){ var store=new Store("ACTIVE"); var s=service(store); assertThatThrownBy(()->s.reset("short","Valid123".toCharArray())).extracting(e->((PasswordRecoveryService.Rejected)e).code).isEqualTo(PasswordRecoveryService.Code.INVALID); assertThatThrownBy(()->s.reset("A".repeat(43),"weak".toCharArray())).extracting(e->((PasswordRecoveryService.Rejected)e).code).isEqualTo(PasswordRecoveryService.Code.POLICY); store.consume=new PasswordRecoveryPort.Token(account,tenant,PasswordRecoveryPort.Purpose.PASSWORD_RESET,new byte[32],Instant.parse("2026-01-01T00:00:00Z")); assertThatThrownBy(()->s.reset("A".repeat(43),"Valid123".toCharArray())).extracting(e->((PasswordRecoveryService.Rejected)e).code).isEqualTo(PasswordRecoveryService.Code.EXPIRED); assertThat(store.resetCalls).isZero(); }
    @Test void rejectsPasswordWhoseUtf8EncodingExceedsBcryptMaximumBeforeHashing(){ var store=new Store("ACTIVE"); var s=service(store); String password="A"+"é".repeat(35)+"1a"; assertThatThrownBy(()->s.reset("A".repeat(43),password.toCharArray())).extracting(e->((PasswordRecoveryService.Rejected)e).code).isEqualTo(PasswordRecoveryService.Code.POLICY); assertThat(store.resetCalls).isZero(); }
    private PasswordRecoveryService service(Store store){return new PasswordRecoveryService(store,store,store,store.sessions,password->"$2a$12$hash",Clock.fixed(Instant.parse("2026-01-01T00:00:00Z"),ZoneOffset.UTC),"01234567890123456789012345678901".getBytes());}
    private final class Store implements PasswordRecoveryPort, IdentityNotificationPort, PasswordRecoveryRequestPort { final String status; Token token,consume; String notificationToken,accepted; int replacements,resetCalls; boolean activation; UUID resetTenant,invalidated; final Sessions sessions=new Sessions(); Store(String status){this.status=status;} public Account findEligibleByIdentifier(String i){return "person@example.test".equals(i)?new Account(account,tenant,status):null;} public void replaceToken(Token t){token=t;replacements++;} public Token consume(byte[] digest,Instant n){var result=consume;consume=null;return result;} public void resetAccount(UUID a,UUID t,String h,boolean x,Instant n){resetCalls++;activation=x;resetTenant=t;} public void invalidateAccountTokens(UUID a,Instant n){invalidated=a;} public void enqueue(UUID a,UUID t,Purpose p,String i,String token,Instant expires){notificationToken=token;} public void accept(String identifier,Instant now){accepted=identifier;} public List<Request> claimDue(Instant now,int limit){return List.of();} public void completed(UUID id,Instant now){} public void retry(UUID id,Instant next){}}
    private static final class Sessions implements RefreshSessionPort { UUID[] revoked; public Resolution resolve(byte[] d){return null;} public Rotation rotate(Resolution f,byte[]a,byte[]b,byte[]c,Instant n){return null;} public void revoke(UUID f,Instant n){} public void revokeAll(UUID a,UUID t,Instant n){revoked=new UUID[]{a,t};} }
}
