package com.nahui.followupbussiness.identityaccess.application;

import com.nahui.followupbussiness.audit.application.RecordAuthenticationAuditCommand;
import com.nahui.followupbussiness.audit.application.port.in.RecordAuthenticationAuditUseCase;
import com.nahui.followupbussiness.identityaccess.application.port.out.*;
import com.nahui.followupbussiness.identityaccess.domain.model.BaseRole;
import com.nahui.followupbussiness.tenancy.application.port.in.CompanyAccessStatusQuery;
import java.time.*; import java.util.*; import javax.crypto.Mac; import javax.crypto.spec.SecretKeySpec; import java.nio.charset.StandardCharsets; import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.*;

class RefreshServiceTest {
 private final UUID account=UUID.randomUUID(), company=UUID.randomUUID(), family=UUID.randomUUID(), client=UUID.randomUUID(); private final Instant now=Instant.parse("2026-08-04T00:00:00Z");
 @Test void rotatesOnceKeepsAbsoluteExpiryAndAuditsTechnicalResult(){var sessions=new Sessions(current());var audit=new Audit();var result=service(sessions,audit).refresh(command());assertThat(result.accessToken()).isEqualTo("jwt");assertThat(result.refreshToken()).hasSize(43);assertThat(sessions.rotated).isTrue();assertThat(sessions.expiry).isEqualTo(now.plus(Duration.ofDays(30)));assertThat(audit.entries).singleElement().extracting(RecordAuthenticationAuditCommand::result).isEqualTo(RecordAuthenticationAuditCommand.Result.REFRESHED);}
 @Test void lateReplayRevokesFamilyAndNeverIssuesCredentials(){var sessions=new Sessions(new RefreshSessionPort.Resolution(family,account,company,"MOBILE",new byte[]{1},null,now.plusSeconds(1),null,now.minusSeconds(6),false));var audit=new Audit();assertThatThrownBy(()->service(sessions,audit).refresh(command())).isInstanceOf(RefreshService.Rejected.class);assertThat(sessions.revoked).isTrue();assertThat(audit.entries).singleElement().extracting(RecordAuthenticationAuditCommand::result).isEqualTo(RecordAuthenticationAuditCommand.Result.REUSED);}
 @Test void revokedExpiredAndInactiveAccountAreRejectedWithoutSuccessToken(){for(var f:List.of(new RefreshSessionPort.Resolution(family,account,company,"MOBILE",new byte[]{1},null,now.plusSeconds(1),now,null,true),new RefreshSessionPort.Resolution(family,account,company,"MOBILE",new byte[]{1},null,now,null,null,true))){assertThatThrownBy(()->service(new Sessions(f),new Audit()).refresh(command())).isInstanceOf(RefreshService.Rejected.class);}}
 @Test void auditFailurePreventsCredentialEmission(){var sessions=new Sessions(current());RecordAuthenticationAuditUseCase failing=c->{throw new IllegalStateException("audit unavailable");};assertThatThrownBy(()->service(sessions,failing).refresh(command())).isInstanceOf(IllegalStateException.class);}
 private RefreshService service(Sessions sessions,RecordAuthenticationAuditUseCase audit){LoginAccountQuery accounts=new LoginAccountQuery(){public Optional<Account> findByIdentifier(String x){return Optional.empty();}public Optional<Account> findById(UUID id){return Optional.of(new Account(account,"h",BaseRole.SELLER,company,"ACTIVE","User","u@example.test"));}}; CompanyAccessStatusQuery companies=id->true; RefreshRateLimitPort limit=(id,ip)->new RefreshRateLimitPort.Decision(true,1);return new RefreshService(sessions,accounts,companies,(a,s,c,r)->"jwt",audit,limit,Clock.fixed(now,ZoneOffset.UTC),"01234567890123456789012345678901".getBytes());}
 private RefreshService.Command command(){return new RefreshService.Command("x".repeat(43),null,"MOBILE",client,UUID.randomUUID(),"127.0.0.1");}
 private RefreshSessionPort.Resolution current(){return new RefreshSessionPort.Resolution(family,account,company,"MOBILE",clientDigest(),null,now.plus(Duration.ofDays(30)),null,null,true);}
 private byte[] clientDigest(){try{var mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec("01234567890123456789012345678901".getBytes(StandardCharsets.UTF_8),"HmacSHA256"));return mac.doFinal(client.toString().getBytes(StandardCharsets.UTF_8));}catch(Exception e){throw new AssertionError(e);}}
 private final class Sessions implements RefreshSessionPort{final RefreshSessionPort.Resolution f;boolean rotated,revoked;Instant expiry;Sessions(RefreshSessionPort.Resolution f){this.f=f;expiry=f.expiresAt();}public Resolution resolve(byte[] x){return f;}public Rotation rotate(Resolution x,byte[] p,byte[] n,byte[] csrf,Instant t){rotated=true;return new Rotation(true,t);}public void revoke(UUID id,Instant n){revoked=true;}}
 private static final class Audit implements RecordAuthenticationAuditUseCase{final List<RecordAuthenticationAuditCommand> entries=new ArrayList<>();public void record(RecordAuthenticationAuditCommand c){entries.add(c);}}
}
