import { Clock3, EllipsisVertical, Eye, PauseCircle, PlayCircle, Search, UserPlus } from "lucide-react";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { DataTable, DataTableIdentity, DataTablePagination, DataTableStatus, type DataTableColumn } from "../../../shared/ui/DataTable";
import type { Company, CompanyPage, CompanyStatus } from "../types";

type Props = { companies: readonly Company[]; page: CompanyPage["page"] | null; search: string; status: CompanyStatus | null; loading: boolean; canManageStatuses: boolean; onSearchChange: (value: string) => void; onStatusChange: (value: CompanyStatus | null) => void; onPageChange: (page: number) => void; onProvision: (company: Company) => void; onAction: (company: Company, action: "detail" | "suspend" | "reactivate") => void };

export function CompanyTable({ companies, page, search, status, loading, canManageStatuses, onSearchChange, onStatusChange, onPageChange, onProvision, onAction }: Props) {
  const [openActionsFor, setOpenActionsFor] = useState<string | null>(null);
  const actionsRef = useRef<HTMLElement>(null);
  useEffect(() => { if (openActionsFor === null) return; const close = (event: PointerEvent) => { if (event.target instanceof Node && !actionsRef.current?.contains(event.target)) setOpenActionsFor(null); }; document.addEventListener("pointerdown", close); return () => document.removeEventListener("pointerdown", close); }, [openActionsFor]);
  return <section className="company-table-card" aria-busy={loading} ref={actionsRef}><div className="company-toolbar"><label className="company-search"><Search aria-hidden="true" /><input type="search" aria-label="Buscar empresa o código" value={search} onChange={(event) => onSearchChange(event.target.value)} placeholder="Buscar empresa o código" /></label><div className="company-filter-group" aria-label="Estado"><strong>Estado:</strong><Filter label="Todas" active={status === null} onClick={() => onStatusChange(null)} /><Filter label="Activas" active={status === "ACTIVE"} onClick={() => onStatusChange("ACTIVE")} /><Filter label="Suspendidas" active={status === "SUSPENDED"} onClick={() => onStatusChange("SUSPENDED")} /></div></div>{loading ? <p className="company-empty" role="status">Cargando empresas…</p> : companies.length === 0 ? <NoResults search={search} /> : <><DataTable ariaLabel="Empresas" items={companies} rowKey={(company) => company.id} columns={companyColumns({ canManageStatuses, openActionsFor, onProvision, onAction, setOpenActionsFor })} />{page && <DataTablePagination page={page.page} totalPages={page.totalPages} onPageChange={onPageChange} ariaLabel="Paginación de empresas" summary={<>Mostrando {companies.length} de {page.totalElements} empresas</>} />}</>}</section>;
}

function companyColumns({ canManageStatuses, openActionsFor, onProvision, onAction, setOpenActionsFor }: { canManageStatuses: boolean; openActionsFor: string | null; onProvision: Props["onProvision"]; onAction: Props["onAction"]; setOpenActionsFor: (value: string | null | ((current: string | null) => string | null)) => void }): readonly DataTableColumn<Company>[] {
  return [{ id: "company", header: "Empresa", label: "Empresa", width: "30%", render: (company) => <DataTableIdentity mark={company.code.slice(0, 2)} primary={company.legalName} secondary={company.tradeName ?? undefined} /> }, { id: "code", header: "Código", label: "Código", width: "13%", render: (company) => <code>{company.code}</code> }, { id: "timezone", header: "Zona horaria", label: "Zona horaria", width: "17%", render: (company) => company.timezone }, { id: "status", header: "Estado", label: "Estado", width: "14%", render: (company) => <DataTableStatus label={company.status === "ACTIVE" ? "Activa" : "Suspendida"} tone={company.status === "ACTIVE" ? "success" : "danger"} /> }, { id: "admins", header: "Administradores", label: "Administradores", width: "14%", align: "center", render: (company) => <button type="button" className="data-table__icon-button" aria-label={`Gestionar administradores de ${company.legalName}`} onClick={() => onProvision(company)} disabled={company.status !== "ACTIVE"}><UserPlus aria-hidden="true" /></button> }, { id: "actions", header: "Acciones", label: "Acciones", width: "12%", align: "center", render: (company) => canManageStatuses ? <div className="company-row-actions"><button type="button" className="data-table__icon-button" aria-label={`Más acciones para ${company.legalName}`} aria-haspopup="menu" aria-expanded={openActionsFor === company.id} onClick={() => setOpenActionsFor((current) => current === company.id ? null : company.id)}><EllipsisVertical aria-hidden="true" /></button>{openActionsFor === company.id && <div className="company-action-menu" role="menu" aria-label={`Acciones de ${company.legalName}`}><ActionMenuItem icon={<Eye aria-hidden="true" />} label="Ver detalle" onSelect={() => { setOpenActionsFor(null); onAction(company, "detail"); }} />{company.status === "ACTIVE" ? <ActionMenuItem icon={<PauseCircle aria-hidden="true" />} label="Suspender empresa" destructive onSelect={() => { setOpenActionsFor(null); onAction(company, "suspend"); }} /> : <ActionMenuItem icon={<PlayCircle aria-hidden="true" />} label="Reactivar empresa" onSelect={() => { setOpenActionsFor(null); onAction(company, "reactivate"); }} />}</div>}</div> : <span>Sin permisos</span> }];
}
function ActionMenuItem({ icon, label, destructive = false, onSelect }: { icon: ReactNode; label: string; destructive?: boolean; onSelect: () => void }) { return <button type="button" role="menuitem" className={destructive ? "company-action-menu__danger" : undefined} onClick={onSelect}>{icon}<span><strong>{label}</strong></span></button>; }
function Filter({ label, active, onClick }: { label: string; active: boolean; onClick: () => void }) { return <button className={`company-filter-chip${active ? " company-filter-chip--active" : ""}`} type="button" aria-pressed={active} onClick={onClick}>{label}</button>; }
function NoResults({ search }: { search: string }) { return <section className="company-empty"><Clock3 aria-hidden="true" /><h2>{search ? "No encontramos empresas" : "Aún no hay empresas creadas"}</h2><p>{search ? `No hay resultados para “${search}”.` : "Crea la primera empresa para comenzar su onboarding."}</p></section>; }
