import { ArrowRight, LockKeyhole, ShieldCheck } from "lucide-react";
import { ConfirmationDialog } from "../../../shared/ui/ConfirmationDialog";
import type { ApiError } from "../../../lib/api";
import type { Seller } from "../types";

function errorMessage(error: ApiError | null) { if (error?.status === 403) return "No tienes permiso para realizar esta acción."; if (error?.status === 404) return "El vendedor ya no está disponible. Actualiza la lista e inténtalo nuevamente."; if (error?.status === 409) return "Finaliza la jornada o recorrido activo antes de volver a intentarlo."; return error ? "No pudimos actualizar el estado. Inténtalo nuevamente." : null; }
export function SellerStatusDialog({ seller, reason, busy, error, onReasonChange, onClose, onConfirm }: { seller: Seller; reason: string; busy: boolean; error: ApiError | null; onReasonChange: (reason: string) => void; onClose: () => void; onConfirm: () => void }) {
  const inactivate = seller.status === "ACTIVE"; const action = inactivate ? "Inactivar" : "Activar"; const invalid = reason.length > 0 && (reason.trim().length < 5 || reason.trim().length > 500); const errorText = errorMessage(error);
  return <ConfirmationDialog appearance="golden" className={inactivate ? "confirmation-dialog--danger" : "confirmation-dialog--info"} module="Vendedores" titleId="seller-status-title" descriptionId="seller-status-description" title={`${action} vendedor`} identity={<SellerIdentity seller={seller} />} message={inactivate ? "Se revocará su acceso y no recibirá nuevas rutas. El vendedor y su historial permanecerán registrados." : "Recuperará el acceso correspondiente. Esta acción no restaura sesiones, rutas ni asignaciones previas automáticamente."} icon={inactivate ? <LockKeyhole aria-hidden="true" /> : <ArrowRight aria-hidden="true" />} tone={inactivate ? "error" : "info"} busy={busy} confirmDisabled={reason.trim().length < 5 || reason.trim().length > 500} busyLabel={inactivate ? "Inactivando…" : "Activando…"} error={errorText} errorTitle={error?.status === 409 ? "No se puede inactivar durante una jornada activa" : "No pudimos actualizar el estado"} correlationId={error?.correlationId} confirmLabel={`${action} vendedor`} cancelLabel="Cancelar" onCancel={onClose} onConfirm={onConfirm} note={<p className="seller-list__confirmation-note"><ShieldCheck aria-hidden="true" />La inactivación nunca elimina al vendedor.</p>} details={<label className="seller-list__reason">Motivo<textarea aria-label="Motivo" value={reason} minLength={5} maxLength={500} required disabled={busy} placeholder="Explica el motivo del cambio" aria-invalid={invalid} aria-describedby="seller-status-reason-help seller-status-reason-count" onChange={(event) => onReasonChange(event.target.value)} /><span id="seller-status-reason-help">Entre 5 y 500 caracteres.</span><small id="seller-status-reason-count" aria-live="polite">{reason.length}/500</small></label>} headerDescription="Confirma el cambio de acceso." />;
}
function SellerIdentity({ seller }: { seller: Seller }) { return <><span className="confirmation-dialog__identity-mark">{seller.displayName.split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase()}</span><span className="confirmation-dialog__identity-copy"><strong>{seller.displayName}</strong><small>{seller.email ?? "Sin correo registrado"}</small></span></>; }
