import { Search } from "lucide-react";
import { VisualSelect } from "../../../shared/ui/VisualSelect";
import type { SellerStatus } from "../types";

type FilterOption = Readonly<{ id: string; label: string }>;

export function SellerFilters({ query, status, supervisorId, territoryId, supervisors, territories, onQueryChange, onStatusChange, onSupervisorChange, onTerritoryChange }: { query: string; status: SellerStatus | null; supervisorId: string | null; territoryId: string | null; supervisors: readonly FilterOption[]; territories: readonly FilterOption[]; onQueryChange: (value: string) => void; onStatusChange: (value: SellerStatus | null) => void; onSupervisorChange: (value: string | null) => void; onTerritoryChange: (value: string | null) => void }) {
  return <div className="seller-list__toolbar"><label className="seller-list__search"><Search aria-hidden="true" /><span className="sr-only">Buscar vendedor</span><input type="search" value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Buscar por nombre, correo o código" /></label><div className="filter-field"><span>Supervisor</span><VisualSelect ariaLabel="Supervisor" value={supervisorId ?? "ALL"} options={[{ value: "ALL", label: "Todos" }, ...supervisors.map(({ id, label }) => ({ value: id, label }))]} onChange={(value) => onSupervisorChange(value === "ALL" ? null : value)} /></div><div className="filter-field"><span>Zona / sede</span><VisualSelect ariaLabel="Zona / sede" value={territoryId ?? "ALL"} options={[{ value: "ALL", label: "Todos" }, ...territories.map(({ id, label }) => ({ value: id, label }))]} onChange={(value) => onTerritoryChange(value === "ALL" ? null : value)} /></div><div className="filter-field"><span>Estado</span><VisualSelect ariaLabel="Estado" value={status ?? "ALL"} options={[{ value: "ALL", label: "Todos" }, { value: "ACTIVE", label: "Activo" }, { value: "INACTIVE", label: "Inactivo" }]} onChange={(value) => onStatusChange(value === "ALL" ? null : value as SellerStatus)} /></div></div>;
}
