package com.nahui.followupbussiness.routing.adapter.in.rest;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.*;
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.LoggerContext;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.read.ListAppender;
import com.nahui.followupbussiness.routing.application.port.in.OptimizeRouteUseCase;
import org.junit.jupiter.api.Test;
import org.slf4j.LoggerFactory;

class RouteOptimizationControllerTest {
 @Test void invalidCommandReturnsRecoverable422WithStablePublicCode(){var service=mock(OptimizeRouteUseCase.class);when(service.optimize(null,null)).thenThrow(new OptimizeRouteUseCase.Invalid("AVAILABILITY_END_MUST_BE_AFTER_START"));var response=new RouteOptimizationController(service).optimize(null,null,"018f4e22-7f40-4b9a-a8f9-5e9a3d7b1c20");var problem=(org.springframework.http.ProblemDetail)response.getBody();assertThat(response.getStatusCode().value()).isEqualTo(422);assertThat(response.getHeaders().getContentType()).isEqualTo(org.springframework.http.MediaType.APPLICATION_PROBLEM_JSON);assertThat(problem.getProperties()).containsEntry("code","AVAILABILITY_END_MUST_BE_AFTER_START").containsEntry("correlationId","018f4e22-7f40-4b9a-a8f9-5e9a3d7b1c20");assertThat(problem.getDetail()).isEqualTo("Request cannot be processed");}
 @Test void missingEndpointReturnsRecoverable422WithStablePublicCode(){var service=mock(OptimizeRouteUseCase.class);when(service.optimize(null,null)).thenThrow(new OptimizeRouteUseCase.Invalid("ROUTE_ENDPOINT_LOCATION_REQUIRED"));var response=new RouteOptimizationController(service).optimize(null,null,"018f4e22-7f40-4b9a-a8f9-5e9a3d7b1c20");var problem=(org.springframework.http.ProblemDetail)response.getBody();assertThat(response.getStatusCode().value()).isEqualTo(422);assertThat(problem.getProperties()).containsEntry("code","ROUTE_ENDPOINT_LOCATION_REQUIRED").containsEntry("correlationId","018f4e22-7f40-4b9a-a8f9-5e9a3d7b1c20");}
 @Test void multipleTerritoriesReturnsSafe422WithoutIdentifiers(){var service=mock(OptimizeRouteUseCase.class);when(service.optimize(null,null)).thenThrow(new OptimizeRouteUseCase.Invalid("MULTIPLE_VISIT_TERRITORIES_NOT_SUPPORTED"));var response=new RouteOptimizationController(service).optimize(null,null,"018f4e22-7f40-4b9a-a8f9-5e9a3d7b1c20");var problem=(org.springframework.http.ProblemDetail)response.getBody();assertThat(response.getStatusCode().value()).isEqualTo(422);assertThat(problem.getProperties()).containsEntry("code","MULTIPLE_VISIT_TERRITORIES_NOT_SUPPORTED").containsEntry("correlationId","018f4e22-7f40-4b9a-a8f9-5e9a3d7b1c20");assertThat(problem.getDetail()).isEqualTo("Request cannot be processed");}
 @Test void forbiddenLogsItsExactSafeDiagnosticButDoesNotExposeIt(){var service=mock(OptimizeRouteUseCase.class);when(service.optimize(null,null)).thenThrow(new OptimizeRouteUseCase.Forbidden("ROUTE_OUTSIDE_ACTOR_PORTFOLIO"));var logs=attachLogs();try{var response=new RouteOptimizationController(service).optimize(null,null,"018f4e22-7f40-4b9a-a8f9-5e9a3d7b1c20");assertThat(response.getStatusCode().value()).isEqualTo(403);assertThat(response.getBody()).isNull();assertThat(logs.list.getFirst().getFormattedMessage()).contains("ROUTE_OUTSIDE_ACTOR_PORTFOLIO","018f4e22-7f40-4b9a-a8f9-5e9a3d7b1c20");}finally{detachLogs(logs);}}
 @Test void sellerTerritoryMismatchReturnsStable422Not403(){var service=mock(OptimizeRouteUseCase.class);when(service.optimize(null,null)).thenThrow(new OptimizeRouteUseCase.Invalid("VISIT_TERRITORY_NOT_ASSIGNED_TO_SELLER"));var response=new RouteOptimizationController(service).optimize(null,null,"018f4e22-7f40-4b9a-a8f9-5e9a3d7b1c20");assertThat(response.getStatusCode().value()).isEqualTo(422);assertThat(response.getBody().toString()).contains("VISIT_TERRITORY_NOT_ASSIGNED_TO_SELLER");}
 @Test void inactiveVisitTerritoryReturnsStable422Not403(){var service=mock(OptimizeRouteUseCase.class);when(service.optimize(null,null)).thenThrow(new OptimizeRouteUseCase.Invalid("VISIT_TERRITORY_INACTIVE"));var response=new RouteOptimizationController(service).optimize(null,null,"018f4e22-7f40-4b9a-a8f9-5e9a3d7b1c20");var problem=(org.springframework.http.ProblemDetail)response.getBody();assertThat(response.getStatusCode().value()).isEqualTo(422);assertThat(problem.getProperties()).containsEntry("code","VISIT_TERRITORY_INACTIVE").containsEntry("correlationId","018f4e22-7f40-4b9a-a8f9-5e9a3d7b1c20");assertThat(problem.getDetail()).isEqualTo("Request cannot be processed");}
 @Test void visitWithoutTerritoryReturnsRecoverable422AndLogsItsExactSafeCode(){var service=mock(OptimizeRouteUseCase.class);when(service.optimize(null,null)).thenThrow(new OptimizeRouteUseCase.Invalid("VISIT_TERRITORY_REQUIRED"));var logs=attachLogs();try{var response=new RouteOptimizationController(service).optimize(null,null,"018f4e22-7f40-4b9a-a8f9-5e9a3d7b1c20");var event=logs.list.getFirst();assertThat(response.getStatusCode().value()).isEqualTo(422);assertThat(response.getBody().toString()).contains("VISIT_TERRITORY_REQUIRED");assertThat(event.getFormattedMessage()).contains("VISIT_TERRITORY_REQUIRED","018f4e22-7f40-4b9a-a8f9-5e9a3d7b1c20");}finally{detachLogs(logs);}}
 @Test void invalidCommandDoesNotExposeOrLogExceptionDetails(){var service=mock(OptimizeRouteUseCase.class);when(service.optimize(null,null)).thenThrow(new OptimizeRouteUseCase.Invalid("java.lang.IllegalStateException: internal route data"));var logs=attachLogs();try{var response=new RouteOptimizationController(service).optimize(null,null,"018f4e22-7f40-4b9a-a8f9-5e9a3d7b1c20");var event=logs.list.getFirst();assertThat(response.getStatusCode().value()).isEqualTo(422);assertThat(response.getBody().toString()).contains("INVALID_OPTIMIZE_REQUEST").doesNotContain("IllegalStateException","internal route data","OptimizeRouteUseCase");assertThat(event.getFormattedMessage()).contains("INVALID_OPTIMIZE_REQUEST","018f4e22-7f40-4b9a-a8f9-5e9a3d7b1c20").doesNotContain("IllegalStateException","internal route data");assertThat(event.getThrowableProxy()).isNull();}finally{detachLogs(logs);}}
 @Test void maliciousCorrelationHeaderIsReplacedAndNeverLoggedOrReturned(){var service=mock(OptimizeRouteUseCase.class);when(service.optimize(null,null)).thenThrow(new OptimizeRouteUseCase.Invalid());String malicious="secret-token\r\nforged";var logs=attachLogs();try{var response=new RouteOptimizationController(service).optimize(null,null,malicious);var correlation=response.getHeaders().getFirst("X-Correlation-Id");var event=logs.list.getFirst();assertThat(correlation).matches("^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$").isNotEqualTo(malicious);assertThat(response.getBody().toString()).doesNotContain("secret-token","forged");assertThat(event.getFormattedMessage()).doesNotContain("secret-token","forged");}finally{detachLogs(logs);}}
 @Test void unavailableProviderReturnsSafe503ProblemAndDiagnostic(){var service=mock(OptimizeRouteUseCase.class);when(service.optimize(null,null)).thenThrow(new OptimizeRouteUseCase.Unavailable("PROVIDER_UNAUTHORIZED"));var logs=attachLogs();try{var response=new RouteOptimizationController(service).optimize(null,null,"018f4e22-7f40-4b9a-a8f9-5e9a3d7b1c20");assertThat(response.getStatusCode().value()).isEqualTo(503);assertThat(response.getHeaders().getFirst("Retry-After")).isEqualTo("1");assertThat(response.getBody().toString()).contains("PROVIDER_UNAUTHORIZED").doesNotContain("matrix");assertThat(logs.list.getFirst().getFormattedMessage()).contains("PROVIDER_UNAUTHORIZED","018f4e22-7f40-4b9a-a8f9-5e9a3d7b1c20");}finally{detachLogs(logs);}}
 @Test void exhaustedQuotaReturnsSafe503RateLimitedCode(){var service=mock(OptimizeRouteUseCase.class);when(service.optimize(null,null)).thenThrow(new OptimizeRouteUseCase.RateLimited());var response=new RouteOptimizationController(service).optimize(null,null,"correlation");assertThat(response.getStatusCode().value()).isEqualTo(503);assertThat(response.getBody().toString()).contains("PROVIDER_RATE_LIMITED").doesNotContain("account");}
 private static ListAppender<ILoggingEvent> attachLogs(){var appender=new ListAppender<ILoggingEvent>();appender.setContext((LoggerContext)LoggerFactory.getILoggerFactory());appender.start();((Logger)LoggerFactory.getLogger(RouteOptimizationController.class)).addAppender(appender);return appender;}
 private static void detachLogs(ListAppender<ILoggingEvent> appender){((Logger)LoggerFactory.getLogger(RouteOptimizationController.class)).detachAppender(appender);appender.stop();}
}
