import { expect, test, type Page, type TestInfo } from "@playwright/test";

const correlationId = "123e4567-e89b-42d3-a456-426614174000";
const territory = { id: "territory-lima", name: "Lima Centro", code: "LIM-CEN", description: "Corredor comercial del Cercado, Breña y principales avenidas del centro histórico.", status: "ACTIVE", assignedSellerCount: 14, createdAt: "2026-09-10T10:42:00-05:00", updatedAt: "2026-09-10T10:42:00-05:00", version: 2 };
const items = [territory, { ...territory, id: "territory-callao", name: "Callao", code: "CALLAO-METROPOLITANO-01", description: "Cobertura del primer puerto y zona industrial del Callao.", assignedSellerCount: 1 }, { ...territory, id: "territory-norte", name: "Lima Norte Histórica", code: "", description: "Conservada para consultas históricas. No recibe nuevas asignaciones.", status: "INACTIVE", assignedSellerCount: 6 }, { ...territory, id: "territory-costa", name: "Costa Verde", description: null, code: "CV", assignedSellerCount: 0 }, { ...territory, id: "territory-este", name: "Lima Este", code: "LIM-EST", description: "Ate, Santa Anita, La Molina y corredores de expansión comercial hacia Chosica.", assignedSellerCount: 9 }];
type Options = { role?: "COMPANY_ADMIN" | "SUPERVISOR"; status?: number; records?: typeof items; loading?: boolean; refreshing?: boolean; mutationStatus?: number; mutationBody?: unknown; mutationDelay?: boolean };
const desktop = { width: 1440, height: 900 };
const mockupPath = "file:///C:/Users/LUIS/OneDrive/Escritorio/FollowUpBussiness/FollwUpBussiness/docs/frontendMockups/FE-037.html";

function identity(role: Options["role"] = "COMPANY_ADMIN") { return { channel: "WEB", credentials: { accessToken: "visual-token", tokenType: "Bearer", expiresIn: 600 }, csrfToken: "c".repeat(43), user: { id: "identity-visual", displayName: "Alex Medina", email: "alex.medina@comercialandina.example", status: "ACTIVE", roles: [role], company: { id: "company-visual", legalName: "Comercial Andina" } } }; }
async function open(page: Page, options: Options = {}) {
  const current = identity(options.role);
  await page.addInitScript(() => { const NativeDate = Date; class VisualDate extends NativeDate { constructor(...args: ConstructorParameters<DateConstructor>) { super(...(args.length ? args : ["2026-09-10T10:42:00-05:00"])); } static now() { return new NativeDate("2026-09-10T10:42:00-05:00").valueOf(); } } window.Date = VisualDate as DateConstructor; });
  await page.route("**/api/**", async route => { const url = new URL(route.request().url()); const list = url.pathname.endsWith("/territories") && route.request().method() === "GET"; const mutation = route.request().method() !== "GET" && url.pathname.includes("/territories"); if (list && options.loading) { await new Promise(resolve => setTimeout(resolve, 10_000)); return; } if (mutation && options.mutationDelay) { await new Promise(resolve => setTimeout(resolve, 10_000)); return; } const body = url.pathname.endsWith("/me") ? current.user : list ? { items: options.records ?? items, page: { page: 12, pageSize: 5, totalElements: 128, totalPages: 26 } } : mutation ? (options.mutationBody ?? {}) : current; await route.fulfill({ status: mutation ? (options.mutationStatus ?? 200) : list ? (options.status ?? 200) : 200, contentType: "application/json", headers: { "X-Correlation-Id": correlationId }, body: JSON.stringify(body) }); });
  await page.goto("/"); await page.getByLabel("Correo o nombre de usuario").fill("alex.medina@comercialandina.example"); await page.locator("#password").fill("correct-password"); await page.getByRole("button", { name: "Iniciar sesión" }).click(); await expect(page.locator(".dashboard-shell")).toBeVisible(); await page.goto(options.role === "SUPERVISOR" ? "/supervisor/territories" : "/company/territories");
  if (options.loading) await expect(page.getByRole("status", { name: "Cargando zonas" })).toBeVisible(); else if (options.status === 403) await expect(page.getByRole("heading", { name: "No tienes permisos" })).toBeVisible(); else if (options.role === "SUPERVISOR") await expect(page.getByText("Vista de solo lectura")).toBeVisible(); else if (options.status === 500) await expect(page.getByRole("heading", { name: "Ocurrió un problema temporal" })).toBeVisible(); else if ((options.records ?? items).length === 0) await expect(page.getByRole("heading", { name: "Aún no hay zonas" })).toBeVisible(); else await expect(page.getByText("Resultados", { exact: true })).toBeVisible();
}
async function snap(page: Page, name: string) { await expect(page).toHaveScreenshot(`fe-037-${name}.png`, { animations: "disabled", maxDiffPixelRatio: 0.02 }); }
async function openEdit(page: Page, record = territory) { await page.getByRole("button", { name: `Más acciones para ${record.name}` }).click(); await page.getByRole("menuitem", { name: "Editar" }).click(); return page.getByRole("dialog", { name: "Editar zona" }); }
async function create(page: Page, valid = true) { await page.getByRole("button", { name: "Crear zona" }).click(); const dialog = page.getByRole("dialog", { name: "Crear zona" }); if (valid) await dialog.getByLabel("Nombre de zona").fill("Zona nueva"); return dialog; }
async function submitCreate(page: Page) { const dialog = await create(page); await dialog.getByRole("button", { name: "Crear zona" }).click(); return dialog; }
async function compare(page: Page, info: TestInfo, name: string, state: string) {
  const size = page.viewportSize(); if (size === null) throw new Error("El viewport visual debe estar definido.");
  const app = await page.screenshot({ animations: "disabled" }); const mockup = await page.context().newPage(); await mockup.setViewportSize(size); await mockup.goto(`${mockupPath}?state=${state}`); const golden = await mockup.screenshot({ animations: "disabled" }); const sheet = await page.context().newPage(); await sheet.setViewportSize({ width: size.width * 2, height: size.height }); await sheet.setContent(`<style>body{margin:0;background:#14110a}main{display:grid;grid-template-columns:repeat(2,${size.width}px);gap:2px}img{width:${size.width}px;height:${size.height}px}</style><main><img alt="Aplicación" src="data:image/png;base64,${app.toString("base64")}"><img alt="Mockup" src="data:image/png;base64,${golden.toString("base64")}"></main>`); const path = info.outputPath(`comparativo-${name}-${size.width}x${size.height}.png`); await sheet.screenshot({ path, animations: "disabled" }); await info.attach(`comparativo-${name}-${size.width}x${size.height}`, { path, contentType: "image/png" }); await mockup.close(); await sheet.close();
}

for (const [name, size] of [["ready-admin", desktop], ["desktop-1024", { width: 1024, height: 768 }], ["tablet-768", { width: 768, height: 1024 }], ["mobile-ready", { width: 390, height: 844 }]] as const) test(`FE-037 ${name}`, async ({ page }, info) => { await page.setViewportSize(size); await open(page); await expect(page.getByRole("button", { name: "Página 13" })).toHaveAttribute("aria-current", "page"); await expect(page.getByRole("button", { name: "Página 12" })).toBeVisible(); await expect(page.getByRole("button", { name: "Página 14" })).toBeVisible(); await snap(page, name); await compare(page, info, name, name); });
test("FE-037 búsqueda de un filtro usa la variante ancha del golden", async ({ page }) => {
  await page.setViewportSize(desktop);
  await open(page);
  const toolbar = page.locator('[data-ui="data-table-toolbar"]');
  await expect(toolbar).toHaveAttribute("data-filter-count", "1");
  await expect(toolbar).toHaveClass(/data-table-toolbar--wide-search/);
  const golden = await page.context().newPage();
  await golden.setViewportSize(desktop);
  await golden.goto(`${mockupPath}?state=ready-admin&guide=0`);
  const widths = async (selector: import("@playwright/test").Locator) => selector.evaluate((element) => [...element.children].map((child) => child.getBoundingClientRect().width));
  const actual = await widths(toolbar);
  const expected = await widths(golden.locator(".zones-filterbar"));
  expect(actual).toHaveLength(2);
  expect(actual.map((width, index) => Math.abs(width - expected[index]))).toEqual([0, 0]);
  const typography = (element: Element) => ({ size: getComputedStyle(element).fontSize, weight: getComputedStyle(element).fontWeight });
  expect(await page.locator(".territory-list__code").first().evaluate(typography)).toEqual(await golden.locator(".zone-code").first().evaluate(typography));
  await golden.close();
});
test("FE-037 readonly-supervisor", async ({ page }, info) => { await page.setViewportSize(desktop); await open(page, { role: "SUPERVISOR" }); await expect(page.getByText("Vista de solo lectura")).toBeVisible(); await expect(page.getByRole("button", { name: "Crear zona" })).toHaveCount(0); await snap(page, "readonly-supervisor"); await compare(page, info, "readonly-supervisor", "readonly-supervisor"); });
test("FE-037 loading", async ({ page }, info) => { await page.setViewportSize(desktop); await open(page, { loading: true }); await snap(page, "loading"); await compare(page, info, "loading", "loading"); });
test("FE-037 refreshing", async ({ page }, info) => { await page.setViewportSize(desktop); await open(page); await page.waitForTimeout(350); await page.route("**/api/territories?**", async () => { await new Promise(resolve => setTimeout(resolve, 10_000)); }); await page.getByRole("button", { name: "Página 26" }).click(); await expect(page.getByRole("status", { name: "Actualizando zonas" })).toBeVisible(); await snap(page, "refreshing"); await compare(page, info, "refreshing", "refreshing"); });
test("FE-037 empty", async ({ page }, info) => { await page.setViewportSize(desktop); await open(page, { records: [] }); await snap(page, "empty"); await compare(page, info, "empty", "empty"); });
test("FE-037 no-results", async ({ page }) => { await page.setViewportSize(desktop); await open(page); await page.getByLabel("Buscar").fill("sin coincidencias"); await expect(page.getByText("Resultados", { exact: true })).toBeVisible(); });
test("FE-037 error", async ({ page }, info) => { await page.setViewportSize(desktop); await open(page, { status: 500, records: [] }); await snap(page, "error"); await compare(page, info, "error", "error"); });
test("FE-037 refresco fallido conserva filas y usa la alerta golden", async ({ page }, info) => {
  await page.setViewportSize(desktop);
  await open(page);
  await expect(page.locator("[data-ui='data-table'] tbody tr")).toHaveCount(5);
  const pattern = "**/api/territories?**";
  const fail = async (route: import("@playwright/test").Route) => route.fulfill({ status: 500, contentType: "application/json", body: "{}" });
  await page.route(pattern, fail);
  await page.getByRole("button", { name: "Página siguiente" }).click();
  const alert = page.locator(".territory-list__stale-error");
  await expect(alert).toBeVisible();
  await expect(alert).toHaveClass(/error-ui-inline-alert--error/);
  await expect(page.locator("[data-ui='data-table'] tbody tr")).toHaveCount(5);
  const golden = await page.context().newPage();
  await golden.setViewportSize(desktop);
  await golden.goto(`${mockupPath}?state=error&guide=0`);
  const props = ["color", "background-color", "border-top-color", "border-top-left-radius", "padding-top", "padding-left"];
  const styles = (element: Element, names: string[]) => Object.fromEntries(names.map(name => [name, getComputedStyle(element).getPropertyValue(name)]));
  expect(await alert.evaluate(styles, props)).toEqual(await golden.locator(".zones-shell > .alert.alert-danger").evaluate(styles, props));
  // FE-037 inherits 14px; the alert in _design-system.html explicitly uses 13px.
  await expect(alert).toHaveCSS("font-size", "13px");
  await page.getByRole("switch", { name: "Modo oscuro" }).click();
  await golden.goto(`${mockupPath}?state=error&theme=dark&guide=0`);
  expect(await alert.evaluate(styles, props)).toEqual(await golden.locator(".zones-shell > .alert.alert-danger").evaluate(styles, props));
  await expect(alert.locator(".error-ui-inline-alert__icon")).toHaveCSS("background-color", "rgba(0, 0, 0, 0)");
  await expect(alert.getByRole("button", { name: "Reintentar" })).toHaveCSS("background-color", "rgba(0, 0, 0, 0)");
  await golden.close();
  await page.getByRole("switch", { name: "Modo oscuro" }).click();
  await compare(page, info, "stale-error", "error");
  await page.unroute(pattern, fail);
  await alert.getByRole("button", { name: "Reintentar" }).click();
  await expect(alert).toHaveCount(0);
});
test("FE-037 forbidden", async ({ page }) => { await page.setViewportSize(desktop); await open(page, { status: 403, records: [] }); await expect(page.getByRole("heading", { name: "No tienes permisos" })).toBeVisible(); await snap(page, "forbidden"); });
test("FE-037 filter-status-open", async ({ page }) => { await page.setViewportSize(desktop); await open(page); await page.getByRole("button", { name: "Estado" }).click(); await expect(page.getByRole("option", { name: "Activas", exact: true })).toBeVisible(); await snap(page, "filter-status-open"); });
for (const [name, record] of [["menu-active", territory], ["menu-inactive", items[2]]] as const) test(`FE-037 ${name}`, async ({ page }, info) => { await page.setViewportSize(desktop); await open(page); await page.getByRole("button", { name: `Más acciones para ${record.name}` }).click(); await expect(page.getByRole("menu", { name: `Acciones de ${record.name}` })).toHaveClass(/table-action-menu--golden/); await snap(page, name); await compare(page, info, name, name); });
test("FE-037 create", async ({ page }, info) => { await page.setViewportSize(desktop); await open(page); await create(page); await snap(page, "create"); await compare(page, info, "create", "create"); });
test("FE-037 create-validation", async ({ page }, info) => { await page.setViewportSize(desktop); await open(page); const dialog = await create(page, false); await dialog.getByRole("button", { name: "Crear zona" }).click(); await expect(dialog.locator("input:invalid")).toHaveCount(1); await snap(page, "create-validation"); await compare(page, info, "create-validation", "create-validation"); });
test("FE-037 create-saving", async ({ page }) => { await page.setViewportSize(desktop); await open(page, { mutationDelay: true }); const dialog = await submitCreate(page); await expect(dialog.getByRole("button", { name: "Guardando…" })).toBeDisabled(); await snap(page, "create-saving"); });
test("FE-037 create-duplicate-error", async ({ page }, info) => { await page.setViewportSize(desktop); await open(page, { mutationStatus: 409, mutationBody: { fieldErrors: [{ field: "code", code: "DUPLICATE" }] } }); const dialog = await submitCreate(page); await expect(dialog.getByRole("alert")).toContainText("Ya existe una zona"); await expect(dialog.getByText(`Correlation ID: ${correlationId}`)).toBeVisible(); await snap(page, "create-duplicate-error"); await compare(page, info, "create-duplicate-error", "create-duplicate-error"); });
test("FE-037 create-validation-422 conserva el borrador", async ({ page }) => { await page.setViewportSize(desktop); await open(page, { mutationStatus: 422, mutationBody: { fieldErrors: [{ field: "name", code: "INVALID" }] } }); const dialog = await submitCreate(page); await expect(dialog).toBeVisible(); await expect(dialog.getByLabel("Nombre de zona")).toHaveValue("Zona nueva"); await expect(dialog.getByRole("alert")).toContainText("Revisa la información ingresada"); await expect(dialog.getByText(`Correlation ID: ${correlationId}`)).toBeVisible(); await snap(page, "create-validation-422"); });
test("FE-037 create-error", async ({ page }) => { await page.setViewportSize(desktop); await open(page, { mutationStatus: 500 }); const dialog = await submitCreate(page); await expect(dialog.getByRole("alert")).toBeVisible(); await snap(page, "create-error"); });
for (const [name, record] of [["edit-active", territory], ["edit-inactive", items[2]]] as const) test(`FE-037 ${name}`, async ({ page }) => { await page.setViewportSize(desktop); await open(page); await openEdit(page, record); await snap(page, name); });
test("FE-037 edit-validation", async ({ page }) => { await page.setViewportSize(desktop); await open(page); const dialog = await openEdit(page); await dialog.getByLabel("Nombre de zona").fill(""); await dialog.getByRole("button", { name: "Guardar cambios" }).click(); await expect(dialog.locator("input:invalid")).toHaveCount(1); await snap(page, "edit-validation"); });
test("FE-037 edit-saving", async ({ page }) => { await page.setViewportSize(desktop); await open(page, { mutationDelay: true }); const dialog = await openEdit(page); await dialog.getByRole("button", { name: "Guardar cambios" }).click(); await expect(dialog.getByRole("button", { name: "Guardando…" })).toBeDisabled(); await snap(page, "edit-saving"); });
for (const [name, status, body, text] of [["edit-duplicate-error", 409, { fieldErrors: [{ field: "name", code: "DUPLICATE" }] }, "Ya existe una zona"], ["edit-conflict", 409, {}, "Los datos cambiaron"], ["edit-not-found", 404, {}, "ya no está disponible"], ["edit-error", 500, {}, "No pudimos guardar"]] as const) test(`FE-037 ${name}`, async ({ page }, info) => { await page.setViewportSize(desktop); await open(page, { mutationStatus: status, mutationBody: body }); const dialog = await openEdit(page); await dialog.getByRole("button", { name: "Guardar cambios" }).click(); await expect(dialog.getByRole("alert")).toContainText(text); await expect(dialog.getByText(`Correlation ID: ${correlationId}`)).toBeVisible(); await snap(page, name); if (name === "edit-conflict") await compare(page, info, name, name); });
test("FE-037 edit-status-open", async ({ page }) => { await page.setViewportSize(desktop); await open(page); const dialog = await openEdit(page); await dialog.getByRole("button", { name: "Estado" }).click(); await expect(page.getByRole("option", { name: "Inactiva" })).toBeVisible(); await snap(page, "edit-status-open"); });
test("FE-037 confirm-inactivate", async ({ page }, info) => { await page.setViewportSize(desktop); await open(page); const dialog = await openEdit(page); await dialog.getByRole("button", { name: "Estado" }).click(); await page.getByRole("option", { name: "Inactiva" }).click(); await dialog.getByRole("button", { name: "Guardar cambios" }).click(); await expect(page.getByRole("alertdialog", { name: "Inactivar zona" })).toBeVisible(); await snap(page, "confirm-inactivate"); await compare(page, info, "confirm-inactivate", "confirm-inactivate"); });
test("FE-037 confirm-inactivate-saving", async ({ page }) => { await page.setViewportSize(desktop); await open(page, { mutationDelay: true }); const dialog = await openEdit(page); await dialog.getByRole("button", { name: "Estado" }).click(); await page.getByRole("option", { name: "Inactiva" }).click(); await dialog.getByRole("button", { name: "Guardar cambios" }).click(); await page.getByRole("button", { name: "Confirmar inactivación" }).click(); await expect(page.getByRole("alertdialog")).toContainText("Inactivando…"); await snap(page, "confirm-inactivate-saving"); });
test("FE-037 confirm-inactivate-error", async ({ page }) => { await page.setViewportSize(desktop); await open(page, { mutationStatus: 500 }); const dialog = await openEdit(page); await dialog.getByRole("button", { name: "Estado" }).click(); await page.getByRole("option", { name: "Inactiva" }).click(); await dialog.getByRole("button", { name: "Guardar cambios" }).click(); await page.getByRole("button", { name: "Confirmar inactivación" }).click(); await expect(page.getByRole("alertdialog")).toContainText("No pudimos inactivar"); await snap(page, "confirm-inactivate-error"); });
for (const [name, action] of [["mobile-menu-open", async (page: Page) => { await page.getByRole("button", { name: `Más acciones para ${territory.name}` }).click(); }], ["mobile-create", async (page: Page) => { await create(page); }], ["mobile-confirm-inactivate", async (page: Page) => { const dialog = await openEdit(page); await dialog.getByRole("button", { name: "Estado" }).click(); await page.getByRole("option", { name: "Inactiva" }).click(); await dialog.getByRole("button", { name: "Guardar cambios" }).click(); }]] as const) test(`FE-037 ${name}`, async ({ page }, info) => { await page.setViewportSize({ width: 390, height: 844 }); await open(page); await action(page); await snap(page, name); await compare(page, info, name, name); });
