import { useMemo, useState, type FormEvent } from "react";
import { ArrowLeft, ArrowRight, Info, Search, Sparkles, X } from "lucide-react";
import { Button } from "../../../shared/ui/Button";
import { DateFilterField } from "../../../shared/ui/DateFilterField";
import { FormAlert } from "../../../shared/ui/FormAlert";
import { ModalAsyncState } from "../../../shared/ui/ModalAsyncState";
import { VisualSelect } from "../../../shared/ui/VisualSelect";
import { WorkflowStepper, type WorkflowStep } from "../../../shared/ui/WorkflowStepper";
import type { ApiError } from "../../../lib/api";
import type { RoutePlanningMode } from "../hooks/useRouteDraft";
import type { Route, RouteCustomerOption, RouteProposalValidation, RouteSellerOption } from "../types";
import { RouteOrderEditor } from "./RouteOrderEditor";
import { RouteProposalControls } from "./RouteProposalControls";

type ProposalVisit = Readonly<{ customerId: string; included: boolean; serviceDurationMinutes: string; priority: string; windowStart: string; windowEnd: string }>;
type Step = "base" | "customers" | "order" | "review" | "constraints";
type Props = {
  mode?: RoutePlanningMode; sellers: readonly RouteSellerOption[]; date: string; sellerId: string; customers: readonly RouteCustomerOption[]; selected: readonly string[]; serviceDurations: Readonly<Record<string, string>>; hasInvalidDurations: boolean; loadingCustomers: boolean; moreCustomers: boolean; suggestionError: ApiError | null; saving: boolean; error: ApiError | null; conflict: boolean;
  availabilityStart: string; availabilityEnd: string; planningWindowLoading: boolean; planningWindowError: ApiError | null; proposalVisits: readonly ProposalVisit[]; proposalValidation: RouteProposalValidation;
  onDate: (value: string) => void; onSeller: (value: string) => void; onSelected: (value: readonly string[]) => void; onServiceDuration: (customerId: string, value: string) => void; onProposalVisit: (customerId: string, patch: Partial<ProposalVisit>) => void; onSubmit: () => void; onGenerateAutomatic: () => void; onLoadMore: () => void; onRetrySuggestions: () => void; onRetryCustomers: () => void; onRetryPlanningWindow: () => void; onClose: () => void; onChangeMode: () => void;
};

const manualLabels = ["Datos base", "Clientes", "Orden y mapa", "Revisar y guardar"] as const;
const automaticLabels = ["Datos base", "Clientes", "Restricciones", "Generar propuesta", "Revisar y guardar"] as const;

export function RoutePlanningWorkflow(props: Props) {
  const automatic = props.mode === "automatic";
  const [step, setStep] = useState<Step>("base");
  const [query, setQuery] = useState("");
  const [manualMobileView, setManualMobileView] = useState<"list" | "map">("list");
  const selectedCustomers = props.selected.flatMap((id) => { const customer = props.customers.find((item) => item.id === id); return customer ? [customer] : []; });
  const available = props.customers.filter((customer) => !props.selected.includes(customer.id) && customer.label.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
  const planningRoute = useMemo<Route>(() => ({ id: "", name: null, date: props.date, sellerId: props.sellerId, status: "DRAFT", updatedAt: "", version: 1, points: selectedCustomers.map((customer, index) => ({ customerId: customer.id, customerName: customer.label, sequence: index + 1, ...(customer.location ? { location: customer.location } : {}) })) }), [props.date, props.sellerId, selectedCustomers]);
  const updateOrder = (from: number, to: number) => { const next = [...props.selected]; const [item] = next.splice(from, 1); if (!item) return; next.splice(to, 0, item); props.onSelected(next); };
  const removeAt = (index: number) => props.onSelected(props.selected.filter((_, itemIndex) => itemIndex !== index));
  const submit = (event: FormEvent) => { event.preventDefault(); if (automatic) props.onGenerateAutomatic(); else props.onSubmit(); };
  const canContinueBase = Boolean(props.date && props.sellerId);
  const selectionLimit = automatic ? 9 : 50;
  const canContinueCustomers = props.selected.length > 0 && props.selected.length <= selectionLimit && !props.hasInvalidDurations;
  const currentIndex = automatic ? (step === "base" ? 0 : step === "customers" ? 1 : step === "constraints" ? (props.saving ? 3 : 2) : 3) : (step === "base" ? 0 : step === "customers" ? 1 : step === "order" ? 2 : 3);
  const labels = automatic ? automaticLabels : manualLabels;
  const steps: readonly WorkflowStep[] = labels.map((label, index) => ({ label, state: index < currentIndex ? "complete" : index === currentIndex ? "current" : "pending" }));
  const previous = () => setStep(step === "customers" ? "base" : step === "constraints" ? "customers" : step === "review" ? "order" : "customers");
  const switchToManual = () => { setStep(props.selected.length > 0 ? "order" : props.date && props.sellerId ? "customers" : "base"); props.onChangeMode(); };
  return <section className="route-page-workflow" aria-labelledby="route-create-title">
    <header className="routes-page__heading route-workflow-heading"><div><span className="route-eyebrow">Planificación operativa</span><h1 id="route-create-title">{automatic ? "Generar propuesta automática" : "Crear ruta manual"}</h1><p>{automatic ? "Configura un borrador base y recibe una propuesta editable. Generar no guarda el orden ni publica la ruta." : "Selecciona clientes y define el orden de visitas según tu criterio. El resultado se guardará como borrador."}</p></div><div className="route-workflow-heading__actions">{automatic ? <Button onClick={switchToManual} leadingIcon={<ArrowRight aria-hidden="true" />}>Ordenar manualmente</Button> : <Button onClick={props.onClose} leadingIcon={<ArrowRight aria-hidden="true" />}>Volver a rutas</Button>}</div></header>
    <form className="route-planning route-workflow-card" onSubmit={submit}>
      <WorkflowStepper label={automatic ? "Progreso de propuesta automática" : "Progreso de planificación manual"} steps={steps} />
      <div className="route-planning__body">
        {props.conflict && <FormAlert><strong>La operación entró en conflicto</strong><p>Conservamos fecha, vendedor, clientes y restricciones para que puedas revisar y reintentar.</p></FormAlert>}
        {props.error && <FormAlert><strong>{props.error.status === 403 ? "No tienes permiso para crear esta ruta" : props.error.status === 503 ? "El optimizador no está disponible" : "No pudimos completar la planificación"}</strong><p>{props.error.status === 403 ? "Tu sesión no autoriza esta operación." : "La información se conserva para que puedas reintentar sin recomenzar."}</p>{props.error.status !== 403 && step !== "constraints" && <Button size="compact" onClick={props.onRetryCustomers}>Reintentar cartera</Button>}</FormAlert>}
        {step === "base" && <section className="route-planning__base" aria-labelledby="route-base-title"><header><span className="route-eyebrow">Datos base</span><h3 id="route-base-title">Programa la ruta</h3><p>Solo se muestran vendedores disponibles en el alcance de tu sesión.</p></header><div className="route-base-grid"><DateFilterField label="Fecha operativa" value={props.date} onValueChange={props.onDate} variant="golden" /><label className="route-field">Vendedor activo<VisualSelect ariaLabel="Vendedor de la ruta" value={props.sellerId || ""} options={[{ value: "", label: "Selecciona un vendedor", disabled: true }, ...props.sellers.filter((seller) => seller.status === "ACTIVE" || seller.status === undefined).map((seller) => ({ value: seller.id, label: seller.label }))]} onChange={props.onSeller} disabled={props.saving} variant="golden" /></label></div><div className="route-info"><Sparkles aria-hidden="true" /><div><strong>Cartera vigente</strong><p>Las sugerencias ayudan a priorizar, pero nunca sustituyen tu selección.</p></div></div></section>}
        {step === "customers" && <section className="route-customer-workspace" aria-label="Selección de clientes"><CustomerPicker {...props} automatic={automatic} available={available} query={query} onQuery={setQuery} selectedCustomers={selectedCustomers} selectionLimit={selectionLimit} /></section>}
        {step === "constraints" && <><div className="route-info"><Info aria-hidden="true" /><div><strong>Generar no guarda ni publica</strong><p>El borrador técnico se prepara internamente al generar. Conservaremos fecha, vendedor, clientes y restricciones si alguna operación falla.</p></div></div><RouteProposalControls route={planningRoute} availabilityStart={props.availabilityStart} availabilityEnd={props.availabilityEnd} planningWindowLoading={props.planningWindowLoading} planningWindowError={props.planningWindowError} visits={props.proposalVisits} proposal={null} validation={props.proposalValidation} saving={props.saving} onRetryPlanningWindow={props.onRetryPlanningWindow} onVisit={props.onProposalVisit} /></>}
        {step === "order" && <section aria-label="Definición del orden manual"><div className="route-mobile-toggle" aria-label="Alternar vista del orden manual"><Button size="compact" variant={manualMobileView === "list" ? "primary" : "secondary"} aria-pressed={manualMobileView === "list"} onClick={() => setManualMobileView("list")}>Secuencia</Button><Button size="compact" variant={manualMobileView === "map" ? "primary" : "secondary"} aria-pressed={manualMobileView === "map"} onClick={() => setManualMobileView("map")}>Mapa</Button></div><div className={`route-manual-order-layout route-manual-order-layout--mobile-${manualMobileView}`}><AvailableCustomers available={available} query={query} onQuery={setQuery} disabled={props.selected.length >= selectionLimit} onAdd={(id) => props.onSelected([...props.selected, id])} /><RouteOrderEditor route={planningRoute} saving={props.saving} onMove={(index, direction) => updateOrder(index, index + direction)} onMoveTo={updateOrder} onRemove={removeAt} previewEnabled={false} markerOnly context="manual" title="Secuencia actual" /></div></section>}
        {step === "review" && <section className="route-manual-review" aria-label="Revisión del borrador manual"><div className="route-info"><div><strong>Revisa el borrador antes de guardar</strong><p>La secuencia textual es la fuente de verdad. El mapa conserva las ubicaciones válidas aunque todavía no exista un recorrido vial.</p></div></div><dl className="route-manual-review__definition"><div><dt>Fecha operativa</dt><dd>{props.date}</dd></div><div><dt>Vendedor</dt><dd>{props.sellers.find((seller) => seller.id === props.sellerId)?.label ?? "No disponible"}</dd></div><div><dt>Visitas</dt><dd>{props.selected.length}</dd></div><div><dt>Estado inicial</dt><dd>Borrador</dd></div></dl><div className="route-manual-review__sequence"><RouteOrderEditor route={planningRoute} saving={props.saving} onMove={(index, direction) => updateOrder(index, index + direction)} onMoveTo={updateOrder} previewEnabled={false} markerOnly context="manual" title="Secuencia a guardar" /></div></section>}
      </div>
      <footer className="route-planning__footer"><span>{step === "order" || step === "review" ? "El mapa no bloquea el guardado; la lista conserva toda la operación." : ""}</span><div>{step !== "base" && step !== "constraints" && <Button onClick={previous} disabled={props.saving}><ArrowLeft aria-hidden="true" />Atrás</Button>}{step === "constraints" && <Button onClick={props.onClose} disabled={props.saving}>Guardar y salir</Button>}{step === "base" && <Button variant="primary" onClick={() => setStep("customers")} disabled={!canContinueBase || props.saving}>Continuar a clientes</Button>}{step === "customers" && <Button variant="primary" onClick={() => setStep(automatic ? "constraints" : "order")} disabled={!canContinueCustomers || props.loadingCustomers || props.saving}>{automatic ? "Continuar a restricciones" : "Continuar a orden y mapa"}</Button>}{step === "order" && <Button variant="primary" onClick={() => setStep("review")} disabled={!canContinueCustomers || props.saving}>Revisar borrador</Button>}{step === "review" && <Button variant="primary" type="submit" disabled={!canContinueCustomers || props.saving}>{props.saving ? "Guardando…" : "Guardar como borrador"}</Button>}{step === "constraints" && <Button variant="primary" type="submit" disabled={props.saving || props.planningWindowLoading || Boolean(props.planningWindowError) || !props.availabilityStart || !props.availabilityEnd || !props.proposalVisits.some((visit) => visit.included)}>{props.saving ? "Generando propuesta…" : "Generar propuesta"}</Button>}</div></footer>
    </form>
  </section>;
}

function CustomerPicker(props: Props & { automatic: boolean; available: readonly RouteCustomerOption[]; query: string; onQuery: (value: string) => void; selectedCustomers: readonly RouteCustomerOption[]; selectionLimit: number }) {
  const updateDuration = (customerId: string, value: string) => {
    props.onServiceDuration(customerId, value);
    if (props.automatic) props.onProposalVisit(customerId, { serviceDurationMinutes: value });
  };
  return <><div className="route-customer-pane"><header><h3>Clientes disponibles</h3><p>{props.customers.length} cargados desde la cartera vigente</p></header><label className="route-search"><span className="sr-only">Buscar cliente</span><Search aria-hidden="true" /><input type="search" value={props.query} onChange={(event) => props.onQuery(event.target.value)} placeholder="Buscar por nombre" /></label>{props.loadingCustomers ? <ModalAsyncState state="loading" title="Cargando clientes" message="Preparamos la cartera y las sugerencias." /> : <div className="route-customer-results">{props.available.map((customer) => <article key={customer.id}><div><strong>{customer.label}</strong>{customer.suggested && <span className="route-badge route-badge--info">Sugerido</span>}{!customer.location && <small>Sin ubicación registrada</small>}</div><Button size="compact" disabled={props.selected.length >= props.selectionLimit} onClick={() => props.onSelected([...props.selected, customer.id])}>Agregar</Button></article>)}{props.available.length === 0 && <p>No hay más clientes que coincidan con la búsqueda.</p>}</div>}{props.moreCustomers && <Button onClick={props.onLoadMore} disabled={props.loadingCustomers}>Cargar más clientes</Button>}{props.suggestionError && <div className="route-inline-notice" role="status"><p>No pudimos cargar sugerencias. La cartera sigue disponible.</p><Button size="compact" onClick={props.onRetrySuggestions}>Reintentar sugerencias</Button></div>}</div><div className="route-customer-pane route-customer-pane--selected"><header><h3>{props.automatic ? "Clientes incluidos" : "Visitas seleccionadas"}</h3><p>{props.selected.length} de {props.selectionLimit} {props.automatic ? "candidatos" : "visitas"}</p></header><ul className={props.automatic ? "route-candidate-selection" : undefined}>{props.selectedCustomers.map((customer, index) => <li key={customer.id}>{!props.automatic && <span className="route-sequence-number">{index + 1}</span>}<div><strong>{customer.label}</strong>{props.automatic && <small>Participará en la propuesta; podrás priorizarlo en el siguiente paso.</small>}<label>{props.automatic ? "Duración estimada (min)" : "Duración (segundos)"}<input aria-label={props.automatic ? `Duración estimada de ${customer.label} (minutos)` : "Duración (segundos)"} type="number" min="1" inputMode="numeric" value={props.serviceDurations[customer.id] ?? ""} onChange={(event) => updateDuration(customer.id, event.target.value)} aria-invalid={!/^\d+$/.test(props.serviceDurations[customer.id] ?? "") || Number(props.serviceDurations[customer.id]) < 1 || undefined} required /></label></div><Button variant="ghost" iconOnly aria-label={`Quitar ${customer.label}`} onClick={() => props.onSelected(props.selected.filter((id) => id !== customer.id))}><X aria-hidden="true" /></Button></li>)}</ul>{props.selected.length === 0 && <p>Agrega al menos un cliente para continuar.</p>}</div></>;
}

function AvailableCustomers({ available, query, onQuery, disabled, onAdd }: { available: readonly RouteCustomerOption[]; query: string; onQuery: (value: string) => void; disabled: boolean; onAdd: (id: string) => void }) {
  return <aside className="route-customer-pane"><header><h3>Clientes disponibles</h3><p>{available.length} clientes aún disponibles</p></header><label className="route-search"><span className="sr-only">Buscar cliente</span><Search aria-hidden="true" /><input type="search" value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Buscar por nombre" /></label><div className="route-customer-results">{available.map((customer) => <article key={customer.id}><div><strong>{customer.label}</strong>{customer.suggested && <span className="route-badge route-badge--info">Sugerido</span>}{!customer.location && <small>Sin ubicación registrada</small>}</div><Button size="compact" disabled={disabled} onClick={() => onAdd(customer.id)}>Agregar</Button></article>)}{available.length === 0 && <p>No hay más clientes que coincidan con la búsqueda.</p>}</div></aside>;
}
