import { type FormEvent } from "react";
import { ModalHeader } from "../../../shared/ui/ModalHeader";
import { ModalSurface } from "../../../shared/ui/ModalSurface";
import { MultiSelect } from "../../../shared/ui/MultiSelect";
import { VisualSelect } from "../../../shared/ui/VisualSelect";
import { DateFilterField } from "../../../shared/ui/DateFilterField";
import { FormAlert } from "../../../shared/ui/FormAlert";
import { ModalAsyncState } from "../../../shared/ui/ModalAsyncState";
import { RouteOrderEditor } from "./RouteOrderEditor";
import type { ApiError } from "../../../lib/api";
import type { Route, RouteCustomerOption, RouteSellerOption } from "../types";

type Props = { sellers: readonly RouteSellerOption[]; date: string; sellerId: string; customers: readonly RouteCustomerOption[]; selected: readonly string[]; loadingCustomers: boolean; moreCustomers: boolean; suggestionError: ApiError | null; saving: boolean; draft: Route | null; error: ApiError | null; conflict: boolean; announcement: string; onDate: (value: string) => void; onSeller: (value: string) => void; onSelected: (value: readonly string[]) => void; onSubmit: () => void; onMove: (index: number, direction: -1 | 1) => void; onMoveTo: (from: number, to: number) => void; onSaveOrder: () => void; onLoadMore: () => void; onRetrySuggestions: () => void; onRetryCustomers: () => void; onClose: () => void };
export function RouteDraftDialog(props: Props) {
  const submit = (event: FormEvent) => { event.preventDefault(); props.onSubmit(); };
  if (props.draft) {
    return <ModalSurface titleId="route-order-title" onDismiss={props.onClose} className="route-detail route-detail--order"><ModalHeader module="Rutas" title="Ordenar borrador" titleId="route-order-title" onClose={props.onClose} closeDisabled={props.saving} /><p className="sr-only" role="status" aria-live="polite">{props.announcement}</p><p className="route-detail__hint" id="route-order-help">Arrastra una visita para cambiar la secuencia. También puedes usar las flechas.</p>{props.conflict && <FormAlert><strong>No pudimos guardar sobre la versión actual</strong><p>Conservamos el orden que preparaste y actualizamos el borrador. Puedes reintentar.</p></FormAlert>}{props.error && <FormAlert><strong>No pudimos guardar el orden</strong><p>Inténtalo nuevamente.</p></FormAlert>}<RouteOrderEditor route={props.draft} saving={props.saving} onMove={props.onMove} onMoveTo={props.onMoveTo} /><footer><button className="route-list__secondary" type="button" onClick={props.onClose} disabled={props.saving}>Cerrar</button><button className="route-list__primary" type="button" onClick={props.onSaveOrder} disabled={props.saving}>{props.saving ? "Guardando…" : "Guardar orden"}</button></footer></ModalSurface>;
  }
  return <ModalSurface titleId="route-create-title" onDismiss={props.onClose} className="route-detail"><ModalHeader module="Rutas" title="Crear borrador" titleId="route-create-title" onClose={props.onClose} closeDisabled={props.saving} /><form onSubmit={submit}><section className="route-detail__scheduled-date"><DateFilterField label="Fecha programada de la ruta" value={props.date} onValueChange={props.onDate} /><p>Elige el día en que el vendedor realizará las visitas.</p></section><label>Vendedor<VisualSelect ariaLabel="Vendedor de la ruta" value={props.sellerId || ""} options={[{ value: "", label: "Selecciona un vendedor", disabled: true }, ...props.sellers.map((seller) => ({ value: seller.id, label: seller.label }))]} onChange={props.onSeller} disabled={props.saving} /></label>{props.loadingCustomers ? <ModalAsyncState state="loading" title="Cargando clientes" message="Estamos preparando la cartera y las sugerencias." /> : <><MultiSelect label="Clientes" ariaLabel="Clientes de la ruta" value={props.selected} options={props.customers.map((customer) => ({ value: customer.id, label: customer.suggested ? `${customer.label} (sugerido)` : customer.label, disabled: props.selected.length >= 50 && !props.selected.includes(customer.id) }))} onChange={props.onSelected} placeholder="Selecciona clientes" />{props.moreCustomers && <button className="route-list__secondary" type="button" onClick={props.onLoadMore}>Cargar más clientes</button>}</>}{props.suggestionError && <div role="status"><p>No pudimos cargar las sugerencias. Tu cartera sigue disponible.</p><button className="route-list__secondary" type="button" onClick={props.onRetrySuggestions} disabled={props.loadingCustomers}>Reintentar sugerencias</button></div>}{props.error && <FormAlert>{props.error.status === 403 ? "No tienes permiso para crear esta ruta." : "No pudimos cargar la cartera de clientes."}<button className="route-list__secondary" type="button" onClick={props.onRetryCustomers}>Reintentar cartera</button></FormAlert>}<p>{props.selected.length} de 50 clientes seleccionados.</p>{props.selected.length >= 50 && <p role="status">Máximo de 50 clientes seleccionado. Puedes desmarcar un cliente para elegir otro.</p>}<footer><button className="route-list__secondary" type="button" onClick={props.onClose} disabled={props.saving}>Cancelar</button><button className="route-list__primary" type="submit" disabled={props.saving || props.loadingCustomers || !props.date || !props.sellerId || props.selected.length === 0 || props.selected.length > 50}>{props.saving ? "Creando…" : "Crear borrador"}</button></footer></form></ModalSurface>;
}
