package com.nahui.followupbussiness.imports.application;

import static org.assertj.core.api.Assertions.*;
import com.nahui.followupbussiness.identityaccess.domain.model.*;
import com.nahui.followupbussiness.imports.application.port.in.CreateCustomerImportUseCase;
import com.nahui.followupbussiness.imports.application.port.out.CustomerImportStore;
import com.nahui.followupbussiness.imports.domain.CustomerImport;
import com.nahui.followupbussiness.outbox.application.port.out.OutboxStore;
import com.nahui.followupbussiness.outbox.domain.*;
import java.time.*; import java.util.*;
import io.micrometer.core.instrument.Counter;
import com.nahui.followupbussiness.audit.application.port.in.RecordAuditEntryUseCase;
import org.junit.jupiter.api.Test;
import static org.mockito.Mockito.mock;

class CustomerImportServiceTest {
 private final UUID tenant=UUID.randomUUID(), user=UUID.randomUUID(), correlation=UUID.randomUUID();
 @Test void adminCreatesTenantBoundJobAndMinimalOutboxEvent() {
  MemoryStore store=new MemoryStore(); List<OutboxEvent> events=new ArrayList<>(); CustomerImportService service=service(store,outbox(events),Clock.fixed(Instant.parse("2026-08-24T00:00:00Z"),ZoneOffset.UTC));
  CustomerImport result=service.create(command("same","abc"),admin(),correlation);
  assertThat(result.status()).isEqualTo(CustomerImport.Status.PENDING); assertThat(result.totalRows()).isNull(); assertThat(result.tenantId()).isEqualTo(tenant); assertThat(events).singleElement().satisfies(e->{assertThat(e.eventType()).isEqualTo("customer-import.requested.v1");assertThat(e.payloadJson()).contains(result.id().toString(),tenant.toString(),correlation.toString()).doesNotContain("abc");});
 }
 @Test void idempotentReplayReturnsExistingButDifferentFileConflicts() { MemoryStore store=new MemoryStore(); CustomerImportService service=service(store,outbox(new ArrayList<>()),Clock.systemUTC()); CustomerImport first=service.create(command("key","a"),admin(),correlation); assertThat(service.create(command("key","a"),admin(),correlation).id()).isEqualTo(first.id()); assertThatThrownBy(()->service.create(command("key","b"),admin(),correlation)).isInstanceOf(CreateCustomerImportUseCase.Conflict.class); }
 @Test void concurrentIdenticalRequestsReturnOneJobAndOneOutboxEvent() throws Exception { MemoryStore store=new MemoryStore(); List<OutboxEvent> events=Collections.synchronizedList(new ArrayList<>()); CustomerImportService service=service(store,outbox(events),Clock.systemUTC()); var start=new java.util.concurrent.CyclicBarrier(2); var pool=java.util.concurrent.Executors.newFixedThreadPool(2); try { var first=pool.submit(()->{start.await();return service.create(command("key","a"),admin(),correlation);}); var second=pool.submit(()->{start.await();return service.create(command("key","a"),admin(),correlation);}); assertThat(first.get().id()).isEqualTo(second.get().id()); assertThat(store.jobs).hasSize(1); assertThat(events).hasSize(1); } finally { pool.shutdownNow(); } }
 @Test void rejectsNonAdminAndOversizedFileBeforeWrites() { MemoryStore store=new MemoryStore(); CustomerImportService service=service(store,outbox(new ArrayList<>()),Clock.systemUTC()); assertThatThrownBy(()->service.create(command("key","a"),new AuthenticatedActor(user,tenant,BaseRole.SELLER),correlation)).isInstanceOf(CreateCustomerImportUseCase.Forbidden.class); assertThatThrownBy(()->service.create(new CreateCustomerImportUseCase.Command("key","a.csv","text/csv","1.0",true,new byte[10*1024*1024+1]),admin(),correlation)).isInstanceOf(CreateCustomerImportUseCase.PayloadTooLarge.class); assertThat(store.jobs).isEmpty(); }
 private AuthenticatedActor admin(){return new AuthenticatedActor(user,tenant,BaseRole.COMPANY_ADMIN);}
 private CreateCustomerImportUseCase.Command command(String key,String body){return new CreateCustomerImportUseCase.Command(key,"a.csv","text/csv","1.0",true,body.getBytes());}
 private static CustomerImportService service(CustomerImportStore store,OutboxStore outbox,Clock clock){return new CustomerImportService(store,outbox,clock,mock(RecordAuditEntryUseCase.class),mock(Counter.class));}
 private static OutboxStore outbox(List<OutboxEvent> events){return new OutboxStore(){public void append(OutboxEvent e){events.add(e);} public List<ClaimedOutboxEvent> claimAvailable(Instant a,Instant b,int c){return List.of();} public boolean markPublished(UUID a,UUID b,Instant c){return false;} public boolean scheduleRetry(UUID a,UUID b,Instant c,String d,String e){return false;} public boolean moveToDlq(UUID a,UUID b,Instant c,PublicationFailureKind d,String e,String f){return false;} public int moveExpiredLeasesToDlqAtMaxAttempts(Instant a){return 0;} public boolean reprocessFromDlq(UUID a,UUID b,Instant c){return false;} public long dlqDepth(){return 0;} public long oldestDlqAgeSeconds(Instant a){return 0;} public long countReadyToPublish(){return 0;} public long oldestReadyAgeSeconds(Instant a){return 0;} public int deleteCompletedBefore(Instant a){return 0;}};}
 static final class MemoryStore implements CustomerImportStore { final List<CustomerImport> jobs=Collections.synchronizedList(new ArrayList<>()); public synchronized Optional<CustomerImport> findByIdempotency(UUID t,UUID u,String key){return jobs.stream().filter(x->x.tenantId().equals(t)&&x.requestedBy().equals(u)&&x.idempotencyKey().equals(key)).findFirst();} public Optional<CustomerImport> findById(UUID t,UUID id){return jobs.stream().filter(x->x.tenantId().equals(t)&&x.id().equals(id)).findFirst();} public List<RowError> findRowErrors(UUID tenant,UUID id){return List.of();} public synchronized Optional<CustomerImport> insertIfAbsent(CustomerImport x,byte[] bytes){if(findByIdempotency(x.tenantId(),x.requestedBy(),x.idempotencyKey()).isPresent())return Optional.empty();jobs.add(x);return Optional.of(x);} public Optional<ClaimedImport> claim(UUID id,UUID tenant){return Optional.empty();} public void complete(UUID id,Integer total,int accepted,int rejected,boolean failed,CustomerImport.FailureReason reason){} public void recordRowErrors(UUID id,List<RowError> errors){} public Optional<CustomerImport> fail(UUID id,UUID tenant){return Optional.empty();} public int purgeExpiredFiles(){return 0;} public int purgeExpiredRowErrors(){return 0;} }
}
